// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2025 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

import { NeedToBeAddressed } from "@prisma/sentencing-server/client";
import _ from "lodash";

export const AUTH_ENDPOINT = "https://api.auntberthaqa.com/v3/authenticate";

// THIS IS GENERATED CODE
// DO NOT MODIFY
// In order to regenerate this object, run the following command:
// nx update-findhelp-labels @sentencing-server/trpc
export const NEEDS_TO_LABELS: Partial<Record<NeedToBeAddressed, string[]>> = {
  AngerManagement: ["anger management"],
  CaseManagement: ["one-on-one support"],
  ClothingAndToiletries: [
    "goods",
    "baby supplies",
    "baby clothes",
    "diapers & formula",
    "clothing",
    "baby clothes",
    "clothes for school",
    "clothes for work",
    "clothing vouchers",
    "home goods",
    "blankets & fans",
    "books",
    "furniture",
    "home fuels",
    "efficient appliances",
    "personal care items",
    "supplies for school",
    "supplies for work",
    "medical supplies",
    "assistive technology",
    "prostheses",
    "personal safety",
    "toys & gifts",
  ],
  Education: [
    "education",
    "help find school",
    "help pay for school",
    "books",
    "clothes for school",
    "financial aid & loans",
    "transportation for school",
    "supplies for school",
    "more education",
    "alternative education",
    "disaster preparedness & response",
    "english as a second language (esl)",
    "financial education",
    "credit counseling",
    "foreclosure counseling",
    "homebuyer education",
    "foreign languages",
    "ged/high-school equivalency",
    "health education",
    "disease management",
    "family planning",
    "nutrition education",
    "parenting education",
    "sex education",
    "understand disability",
    "understand mental health",
    "safety education",
    "supported employment",
    "special education",
    "tutoring",
    "civic engagement",
    "environmental education",
    "college readiness",
    "youth development",
    "preschool",
    "screening & exams",
    "citizenship & immigration",
    "ged/high-school equivalency",
    "english as a second language (esl)",
    "skills & training",
    "basic literacy",
    "computer class",
    "daily life skills",
    "interview training",
    "resume development",
    "skills assessment",
    "specialized training",
  ],
  FamilyServices: [
    "daytime care",
    "head start",
    "early childhood intervention",
    "adult daycare",
    "after school care",
    "before school care",
    "childcare",
    "help find childcare",
    "help pay for childcare",
    "day camp",
    "preschool",
    "relief for caregivers",
  ],
  FoodInsecurity: [
    "food",
    "community gardens",
    "emergency food",
    "food delivery",
    "food pantry",
    "meals",
    "help pay for food",
    "government food benefits",
    "nutrition education",
    "emergency food",
    "help pay for food",
    "government food benefits",
  ],
  FinancialAssistance: [
    "loans",
    "personal loans",
    "business loans",
    "government benefits",
    "disability benefits",
    "government food benefits",
    "retirement benefits",
    "understand government programs",
    "unemployment benefits",
    "financial assistance",
    "help pay for childcare",
    "help pay for food",
    "government food benefits",
    "help pay for healthcare",
    "disability benefits",
    "discounted healthcare",
    "health insurance",
    "medical supplies",
    "prescription assistance",
    "transportation for healthcare",
    "help pay for housing",
    "help pay for utilities",
    "help pay for internet or phone",
    "home & renters insurance",
    "help pay for school",
    "books",
    "clothes for school",
    "financial aid & loans",
    "transportation for school",
    "supplies for school",
    "help pay for transit",
    "help pay for gas",
    "bus passes",
    "help pay for work expenses",
  ],
  Healthcare: [
    "medical care",
    "primary care",
    "alternative medicine",
    "medical supplies",
    "prostheses",
    "assistive technology",
    "support & service animals",
    "skilled nursing",
    "checkup & test",
    "disability screening",
    "disease screening",
    "hearing tests",
    "pregnancy tests",
    "exercise & fitness",
    "personal hygiene",
    "prevent & treat",
    "early childhood intervention",
    "counseling",
    "hiv treatment",
    "pain management",
    "disease management",
    "nursing home",
    "physical therapy",
    "occupational therapy",
    "speech therapy",
    "specialized therapy",
    "vaccinations",
    "in-home support",
    "residential treatment",
    "outpatient treatment",
    "hospital treatment",
    "medication management",
    "help find healthcare",
    "vision care",
    "help pay for healthcare",
    "disability benefits",
    "discounted healthcare",
    "health insurance",
    "prescription assistance",
    "transportation for healthcare",
    "dental care",
  ],
  GeneralReEntrySupport: [
    "support network",
    "counseling",
    "help hotlines",
    "home visiting",
    "in-home support",
    "mentoring",
    "one-on-one support",
    "peer support",
    "peer recovery coaching",
    "spiritual support",
    "support groups",
    "12-step",
    "bereavement",
    "parenting education",
    "virtual support",
    "navigating the system",
    "help fill out forms",
    "case management",
    "daily life skills",
  ],
  HousingOpportunities: [
    "housing",
    "temporary shelter",
    "help find housing",
    "help pay for housing",
    "help pay for utilities",
    "help pay for internet or phone",
    "home & renters insurance",
    "housing vouchers",
    "maintenance & repairs",
    "efficiency upgrades",
    "health & safety",
    "pest control",
    "housing advice",
    "foreclosure counseling",
    "homebuyer education",
    "residential housing",
    "long-term housing",
    "assisted living",
    "independent living",
    "nursing home",
    "public housing",
    "safe housing",
    "short-term housing",
    "nursing home",
    "sober living",
  ],
  JobTrainingOrOpportunities: [
    "work",
    "help find work",
    "job placement",
    "supported employment",
    "help pay for work expenses",
    "clothes for work",
    "retirement benefits",
    "supplies for work",
    "unemployment benefits",
    "skills & training",
    "basic literacy",
    "computer class",
    "ged/high-school equivalency",
    "interview training",
    "resume development",
    "skills assessment",
    "specialized training",
    "supported employment",
    "workplace rights",
  ],
  MentalHealth: [
    "mental health care",
    "anger management",
    "bereavement",
    "counseling",
    "group therapy",
    "substance abuse counseling",
    "family counseling",
    "individual counseling",
    "medications for mental health",
    "mental health evaluation",
    "outpatient treatment",
    "hospital treatment",
    "residential treatment",
    "psychiatric emergency services",
    "understand mental health",
    "support & service animals",
    "psychiatric emergency services",
    "counseling",
    "understand mental health",
    "medication management",
  ],
  SubstanceUse: [
    "addiction & recovery",
    "12-step",
    "detox",
    "outpatient treatment",
    "residential treatment",
    "sober living",
    "drug testing",
    "substance abuse counseling",
    "peer recovery coaching",
    "medications for addiction",
    "residential treatment",
    "12-step",
  ],
  Transportation: [
    "transit",
    "help pay for transit",
    "bus passes",
    "help pay for gas",
    "help pay for car",
    "transportation",
    "transportation for healthcare",
    "transportation for school",
  ],
};

// Get all of the relevant service tags as a comma separated string
export const RELEVANT_SERVICE_TAGS = _(NEEDS_TO_LABELS)
  .values()
  .filter((v) => v !== undefined)
  .flatten()
  .uniq()
  .join();
