# SOPS allows us to store encrypted secrets files in our git repository
# Configure SOPS to use the GCP KMS key provisioned for encryption / decryption
# https://github.com/getsops/sops
creation_rules:
  - path_regex: 'apps/@jii/.+\.enc\.yaml$'
    gcp_kms: projects/recidiviz-jii-staging/locations/us-central1/keyRings/recidiviz-jii-staging-sops/cryptoKeys/recidiviz-jii-staging-sops-key
  - path_regex: 'apps/public-pathways/.+\.enc\.yaml$'
    gcp_kms: projects/public-pathways-staging/locations/us-central1/keyRings/public-pathways-staging-sops/cryptoKeys/public-pathways-staging-sops-key
  - path_regex: '\.enc\.yaml$'
    gcp_kms: projects/recidiviz-dashboard-staging/locations/us-central1/keyRings/pulse-dashboards-sops/cryptoKeys/pulse-dashboards-sops-key
