language: node_js
node_js:
- lts/*
before_install:
- openssl aes-256-cbc -K $encrypted_49f5b54eb380_key -iv $encrypted_49f5b54eb380_iv
  -in recidiviz-gae-api-key.json.enc -out recidiviz-gae-api-key.json -d
install:
- yarn install
script:
- yarn test
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
- yarn build
deploy:
  provider: gae
  config: pulse-dashboards-staging.yaml
  keyfile: recidiviz-gae-api-key.json
  project: recidiviz-123
  on: master
  skip_cleanup: true
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  slack:
    secure: xdEE3sa61p6k+DzmUoJBglIxIbX9Q9OirZZU8n6a823t4zsSeiTmCS/0t5Uayx+tNa30zZ689twFlKxR/juq8NqMTbR0TCOg7jfeA2f1hH1Wm/1J5c826N5fN6f2Nc9qMLRpeLuAnLklRSolAyE1n+1XSsMCBBIX+apurvNGFOfoqJmcEBkWezLXM0pILbmEG3OOTALbSIA9Fyw9AYWOAByeykfMU0mq7dyjIme3ACW0IiYh4qH18LotopwGifrQ+XSBvYqAAZ4U7HXb33KeXJoJBQIFtvJTHtqGXixoaLXoMmpU8R7jrqSGopR/XGJ9XDJkgKOOFMDgopsyzzxNPWqwZBrjLgXlMUb4iC9QYCMRDmz4MIqA5sVmUsxhdOJKRlbBY7zsCbsJHR3Mbp5SXNLvv9zT+Pd63vV5qcjmm/nVumdlt/rrlYbzgPIYHHnoO8huXaJI6ROx7KeQDmf/TEL85Ei/sKdPoaSqsfd4LK9AlB1mjdPHBVKp7BZjbfaaRNUG8a9qq91FnaUvIbdouTkBIs0JiENGB3Owd9G3M4FLacPklmk40gSYazV6z61N/bZLn6ATaQgFdKRL5SR3S5KT1vKi0MomHxVhiowkNWemuCFIcyFpmf6StzMm0HE+OIver1HV8/eyy1Httc31xohPPKt4/CBGPKdZLrKiBPM=
