language: node_js
node_js:
  - "lts/*"
install:
  - yarn install
script:
  - yarn test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  # TODO: Create build and deploy to GAE as part of resolving issue #23
  # - yarn build
cache:
  yarn: true
  directories:
    - "node_modules"
