"""add intake token

Revision ID: 028e851375b7
Revises: e2c9f2b0230d
Create Date: 2025-04-18 07:21:42.379008

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028e851375b7'
down_revision: Union[str, None] = 'e2c9f2b0230d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intaketoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('intake_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intaketoken_intake_id'), 'intaketoken', ['intake_id'], unique=False)
    op.drop_constraint('assessment_intake_id_fkey', 'assessment', type_='foreignkey')
    op.create_foreign_key(None, 'assessment', 'intake', ['intake_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessment', type_='foreignkey')
    op.create_foreign_key('assessment_intake_id_fkey', 'assessment', 'intake', ['intake_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_intaketoken_intake_id'), table_name='intaketoken')
    op.drop_table('intaketoken')
    # ### end Alembic commands ###
