"""adds processing intake status

Revision ID: 0be418f5aee5
Revises: f714aeffa418
Create Date: 2026-02-12 15:39:02.774107

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be418f5aee5'
down_revision: Union[str, None] = 'f714aeffa418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new 'processing' value to intake_status_enum
    # Note: This must be done outside a transaction in PostgreSQL
    op.execute("ALTER TYPE intake_status_enum ADD VALUE IF NOT EXISTS 'processing'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL does not support removing enum values directly.
    # If needed, this would require recreating the enum type, which is complex
    # and can impact existing data. For now, leaving the enum value in place.
    pass
    # ### end Alembic commands ###
