"""add_assessment_type_to_intake_section

Revision ID: 16bf98f18f3c
Revises: 0fcf443b0c25
Create Date: 2025-06-06 12:46:41.850451

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bf98f18f3c'
down_revision: Union[str, None] = '0fcf443b0c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assessment_intake_id_fkey', 'assessment', type_='foreignkey')
    op.create_foreign_key(None, 'assessment', 'intake', ['intake_id'], ['id'])

    # Add assessment_type column with default value
    op.add_column('intakesection', sa.Column('assessment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='lsir'))

    # Update existing records to have 'lsir' assessment_type (they are all LSIR sections)
    op.execute("UPDATE intakesection SET assessment_type = 'lsir' WHERE assessment_type IS NULL")

    # Remove the server default after updating existing records
    op.alter_column('intakesection', 'assessment_type', server_default=None)

    op.create_unique_constraint('unique_title_assessment_type', 'intakesection', ['title', 'assessment_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_title_assessment_type', 'intakesection', type_='unique')
    op.drop_column('intakesection', 'assessment_type')
    op.drop_constraint('assessment_intake_id_fkey', 'assessment', type_='foreignkey')
    op.create_foreign_key('assessment_intake_id_fkey', 'assessment', 'intake', ['intake_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
