"""generation type

Revision ID: 1a96d0bdd3e9
Revises: 6d4a11c0fbd0
Create Date: 2024-10-24 10:08:56.342500

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a96d0bdd3e9'
down_revision: Union[str, None] = '6d4a11c0fbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('gen_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='automated'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plangeneration', 'gen_type')
    # ### end Alembic commands ###
