"""assessment type

Revision ID: 1b73be1e6e36
Revises: b920cd908db2
Create Date: 2025-05-30 10:15:30.503069

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b73be1e6e36'
down_revision: Union[str, None] = 'b920cd908db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('assessment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assessmenttree', sa.Column('assessment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessmenttree', 'assessment_type')
    op.drop_column('assessment', 'assessment_type')
    # ### end Alembic commands ###
