"""add_plan_generation_resource_association

Revision ID: 20f66307c5f8
Revises: c52c45b26f4f
Create Date: 2026-04-21 14:02:17.405746

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f66307c5f8'
down_revision: Union[str, None] = 'c52c45b26f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plangenerationresourceassociation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_generation_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sa.Enum('ADD', 'REMOVE', name='resource_association_action_enum'), nullable=False),
    sa.Column('action_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_generation_id'], ['plangeneration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plangenerationresourceassociation_plan_generation_id'), 'plangenerationresourceassociation', ['plan_generation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plangenerationresourceassociation_plan_generation_id'), table_name='plangenerationresourceassociation')
    op.drop_table('plangenerationresourceassociation')
    # ### end Alembic commands ###
