"""add notify true on regeneration

Revision ID: 25e1e88178eb
Revises: eb68d94e870b
Create Date: 2025-07-24 21:32:05.393424

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e1e88178eb'
down_revision: Union[str, None] = 'eb68d94e870b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('regeneration_notify', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plangeneration', 'regeneration_notify')
    # ### end Alembic commands ###
