"""add_order_field_to_intake_section

Revision ID: 284ac3721439
Revises: bf5d5c7e1d10
Create Date: 2025-06-09 20:06:07.407736

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284ac3721439'
down_revision: Union[str, None] = 'bf5d5c7e1d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('intakesection', sa.Column('order', sa.Integer(), nullable=True))

    # Update existing records with default order values based on their assessment type
    # LSIR sections
    op.execute("""
        UPDATE intakesection
        SET "order" = CASE title
            WHEN 'Employment' THEN 0
            WHEN 'Education' THEN 1
            WHEN 'Financial' THEN 2
            WHEN 'Family and Marital Relationships' THEN 3
            WHEN 'Accommodation' THEN 4
            WHEN 'Leisure and Recreation' THEN 5
            WHEN 'Companions' THEN 6
            WHEN 'Alcohol and Drug Use' THEN 7
            ELSE 0
        END
        WHERE assessment_type = 'lsir'
    """)

    # ORAS_RT sections
    op.execute("""
        UPDATE intakesection
        SET "order" = CASE title
            WHEN 'Personal Demographics' THEN 0
            WHEN 'Criminal History' THEN 1
            WHEN 'Education' THEN 2
            WHEN 'Employment' THEN 3
            WHEN 'Financial and Marital Status' THEN 4
            WHEN 'Accommodation' THEN 5
            WHEN 'Social Support and Family Relationships' THEN 6
            WHEN 'Criminal Attitudes and Behavioral Patterns' THEN 7
            ELSE 0
        END
        WHERE assessment_type = 'oras_rt'
    """)

    # Make the column non-nullable
    op.alter_column('intakesection', 'order', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intakesection', 'order')
    # ### end Alembic commands ###
