"""add_intake_locked_fields

Revision ID: 2e6e648aced5
Revises: cc68c51f3ce6
Create Date: 2026-04-20 16:50:01.127748

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6e648aced5'
down_revision: Union[str, None] = 'cc68c51f3ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake', sa.Column('locked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('intake', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('intake', sa.Column('locked_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake', 'locked_reason')
    op.drop_column('intake', 'locked_at')
    op.drop_column('intake', 'locked')
    # ### end Alembic commands ###
