"""Creates ai persona models

Revision ID: 2edc3407cdb2
Revises: 0be418f5aee5
Create Date: 2026-03-10 16:01:42.286367

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2edc3407cdb2'
down_revision: Union[str, None] = '0be418f5aee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_persona',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('background', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenges', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('communication_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_persona_name'), 'ai_persona', ['name'], unique=False)
    op.create_table('ai_intake_trigger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('intake_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('from_template', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['ai_persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_intake_trigger_intake_id'), 'ai_intake_trigger', ['intake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_intake_trigger_intake_id'), table_name='ai_intake_trigger')
    op.drop_table('ai_intake_trigger')
    op.drop_index(op.f('ix_ai_persona_name'), table_name='ai_persona')
    op.drop_table('ai_persona')
    # ### end Alembic commands ###
