"""edited manually plan

Revision ID: 312dcc5dfe92
Revises: 028e851375b7
Create Date: 2025-05-01 14:47:02.155950

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312dcc5dfe92'
down_revision: Union[str, None] = '028e851375b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('edited_manually', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'edited_manually')
    # ### end Alembic commands ###
