"""adds-assessment-tree

Revision ID: 3163b8f46945
Revises: 84f38fb01864
Create Date: 2025-02-11 13:05:12.550716

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3163b8f46945'
down_revision: Union[str, None] = '84f38fb01864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessmenttree',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('current_revision_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessmenttree_name'), 'assessmenttree', ['name'], unique=True)
    op.create_table('assessmenttreerevision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('assessment_tree_id', sa.Uuid(), nullable=False),
    sa.Column('mermaid_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('additional_structured_data', sa.JSON(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_tree_id'], ['assessmenttree.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessmenttreerevision')
    op.drop_index(op.f('ix_assessmenttree_name'), table_name='assessmenttree')
    op.drop_table('assessmenttree')
    # ### end Alembic commands ###
