"""decision tree

Revision ID: 340efacf06b8
Revises: 6d4e21739f82
Create Date: 2024-10-03 10:13:26.482262

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340efacf06b8'
down_revision: Union[str, None] = '6d4e21739f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisiontree',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criterias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('current_revision_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisiontree_id'), 'decisiontree', ['id'], unique=True)
    op.create_index(op.f('ix_decisiontree_name'), 'decisiontree', ['name'], unique=True)
    op.create_table('decisiontreerevision',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('decision_tree_id', sa.Uuid(), nullable=False),
    sa.Column('mermaid_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['decision_tree_id'], ['decisiontree.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisiontreerevision_id'), 'decisiontreerevision', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisiontreerevision_id'), table_name='decisiontreerevision')
    op.drop_table('decisiontreerevision')
    op.drop_index(op.f('ix_decisiontree_name'), table_name='decisiontree')
    op.drop_index(op.f('ix_decisiontree_id'), table_name='decisiontree')
    op.drop_table('decisiontree')
    # ### end Alembic commands ###
