"""add_resource_changes_to_plan_generation

Revision ID: 35af5feee67b
Revises: 1f0ce6e25c9f
Create Date: 2024-11-13 14:06:38.219421

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35af5feee67b'
down_revision: Union[str, None] = 'dd34ed9ea02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('resource_to_remove_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plangeneration', sa.Column('resource_to_add_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plangeneration', 'resource_to_add_id')
    op.drop_column('plangeneration', 'resource_to_remove_id')
    # ### end Alembic commands ###
