"""blobfile not null

Revision ID: 3a3caf44e9a4
Revises: 631222ca3d52
Create Date: 2024-10-04 13:04:20.831076

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a3caf44e9a4'
down_revision: Union[str, None] = '631222ca3d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planasset', 'file_blob',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('planasset', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planasset', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('planasset', 'file_blob',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
