"""removing assessment_summarize_template from output

Revision ID: 3bd66a29411c
Revises: 0de3cec45123
Create Date: 2026-01-26 14:12:49.173927

"""
from pathlib import Path
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd66a29411c'
down_revision: Union[str, None] = '09521271ecd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    yaml_path = (
            Path(__file__).parent
            / "../../app/core/data_config/output_configs/summary-default-v0.yaml"
    )

    with open(yaml_path, "r") as f:
        yaml_content = f.read()

    # Escape single quotes for SQL
    yaml_content_escaped = yaml_content.replace("'", "''")

    # Update existing plandefault v0 config
    op.execute(
        f"""
            UPDATE outputconfig
            SET
                config_yaml = '{yaml_content_escaped}',
                updated_at = NOW()
            WHERE
                code = 'intakesummarydefault'
                AND version = 0
            """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
