"""add intake relationships

Revision ID: 422941983959
Revises: 2314f2d12fd6
Create Date: 2025-12-09 14:56:00.593258

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422941983959'
down_revision: Union[str, None] = '746b7d9a6c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('intake_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'plan', 'intake', ['intake_id'], ['id'])
    # Get a connection
    connection = op.get_bind()

    # Query all plans without intake_id and join with intake table to get the intake_id
    plans_query = sa.text("""
        SELECT p.id as plan_id, i.id as intake_id
        FROM plan p
        JOIN intake i ON p.client_pseudo_id = i.client_pseudo_id
        WHERE p.intake_id IS NULL
    """)
    plans_without_intakes = connection.execute(plans_query).fetchall()

    # Update each plan with its corresponding intake_id
    for plan in plans_without_intakes:
        update_query = sa.text("""
            UPDATE plan
            SET intake_id = :intake_id
            WHERE id = :plan_id
        """)
        connection.execute(update_query, {"intake_id": plan.intake_id, "plan_id": plan.plan_id})



    op.drop_column('plan', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('type', sa.VARCHAR(), server_default=sa.text("'live'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'plan', type_='foreignkey')
    op.drop_column('plan', 'intake_id')
    # ### end Alembic commands ###
