"""removing_scoring_from_yamls

Revision ID: 44a6522adfe5
Revises: 422941983959
Create Date: 2026-01-14 11:12:17.870686

"""
from typing import Sequence, Union
from pathlib import Path

import yaml
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a6522adfe5'
down_revision: Union[str, None] = '422941983959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    base_path = (
            Path(__file__).parent
            / "../../app/core/data_config/assessment_configs"
    )

    yaml_files = sorted(base_path.glob("*.yaml"))
    print(yaml_files, "yaml_files")
    if not yaml_files:
        raise RuntimeError("No YAML files found in assessment_configs")

    configs = []

    # 1. Parse & validate
    for yaml_path in yaml_files:
        raw_yaml = yaml_path.read_text()
        parsed = yaml.safe_load(raw_yaml) or {}

        metadata = parsed.get("metadata") or {}
        state_code = metadata.get("state_code")
        code = metadata.get("code")
        version = metadata.get("version")
        if state_code is None or code is None or version is None:
            raise ValueError(f"Incomplete metadata in {yaml_path.name}")

        configs.append({
            "state_code": state_code,
            "code": code.lower(),
            "version": version,
            "config_yaml": raw_yaml,
            "file": yaml_path.name,
        })

    # 2. Transactional update
    for config in configs:
        print(f"Updating {config['file']}")
        result = conn.execute(
            sa.text("""
                    UPDATE assessmentconfig
                    SET config_yaml = :config_yaml,
                        updated_at  = NOW()
                    WHERE state_code = :state_code
                      AND code = :code
                      AND version = :version
                    """),
            config,
        )

        if result.rowcount == 0:
            raise RuntimeError(
                f"No assessmentconfig found for "
                f"{config['state_code']} {config['code']} {config['version']} "
                f"(from {config['file']})"
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
