"""Add cascade delete to intake foreign keys

Revision ID: 464d419329c5
Revises: f3142bcfd92e
Create Date: 2025-09-25 20:01:42.051908

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464d419329c5'
down_revision: Union[str, None] = 'f3142bcfd92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('intakemessage_intake_id_fkey', 'intakemessage', type_='foreignkey')
    op.create_foreign_key(None, 'intakemessage', 'intake', ['intake_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('intaketoken_intake_id_fkey', 'intaketoken', type_='foreignkey')
    op.create_foreign_key(None, 'intaketoken', 'intake', ['intake_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intaketoken', type_='foreignkey')
    op.create_foreign_key('intaketoken_intake_id_fkey', 'intaketoken', 'intake', ['intake_id'], ['id'])
    op.drop_constraint(None, 'intakemessage', type_='foreignkey')
    op.create_foreign_key('intakemessage_intake_id_fkey', 'intakemessage', 'intake', ['intake_id'], ['id'])
    # ### end Alembic commands ###
