"""remove_oms_doc_id

Revision ID: 4d9775c687df
Revises: 95ab1e381a66
Create Date: 2025-03-20 16:58:43.758320

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9775c687df'
down_revision: Union[str, None] = '95ab1e381a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'oms_doc_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('oms_doc_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
