"""completed_intake_date

Revision ID: 4e424a4f4e3a
Revises: 8fe8527ba3ca
Create Date: 2025-11-27 09:32:49.735226

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e424a4f4e3a'
down_revision: Union[str, None] = '8fe8527ba3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake', 'completed_at')
    # ### end Alembic commands ###
