"""transcription feature

Revision ID: 5131a8c909b9
Revises: 25e1e88178eb
Create Date: 2025-07-29 13:13:45.486709

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

intake_type_enum = sa.Enum('transcription', 'conversation', name='intake_type_enum')
recording_status_enum = sa.Enum("created", "recording", "paused", "processing", "error", "completed", name="recording_status_enum")

# revision identifiers, used by Alembic.
revision: str = '5131a8c909b9'
down_revision: Union[str, None] = '25e1e88178eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ## creating and updating enums manually
    intake_type_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intake_id', sa.Uuid(), nullable=False),
    sa.Column('audio_chunks_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('created', 'recording', 'paused', 'processing', 'error', 'completed', name='recording_status_enum'), nullable=False),
    sa.Column('gcs_bucket_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gcs_chunks_folder', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gcs_final_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('transcription_approved', sa.Boolean(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['recording_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'chunk_index', name='uq_session_chunk')
    )
    op.drop_constraint('assessmentrevisionlink_assessment_id_fkey', 'assessmentrevisionlink', type_='foreignkey')
    op.drop_constraint('assessmentrevisionlink_assessment_tree_revision_id_fkey', 'assessmentrevisionlink', type_='foreignkey')
    op.create_foreign_key('assessmentrevisionlink_assessment_id_fkey', 'assessmentrevisionlink', 'assessment', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('assessmentrevisionlink_assessment_tree_revision_id_fkey', 'assessmentrevisionlink', 'assessmenttreerevision', ['assessment_tree_revision_id'], ['id'], ondelete='CASCADE')
    op.alter_column('clientintakesection', 'intake_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('clientintakesection', 'intake_section_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('clientintakesection_intake_id_fkey', 'clientintakesection', type_='foreignkey')
    op.drop_constraint('clientintakesection_intake_section_id_fkey', 'clientintakesection', type_='foreignkey')
    op.create_foreign_key('clientintakesection_intake_id_fkey', 'clientintakesection', 'intakesection', ['intake_section_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('clientintakesection_intake_section_id_fkey', 'clientintakesection', 'intake', ['intake_id'], ['id'], ondelete='SET NULL')
    op.add_column('intake', sa.Column('intake_type', sa.Enum('transcription', 'conversation', name='intake_type_enum'), nullable=True))
    op.alter_column('intake_section_revision', 'intake_section_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_intake_section_revision_section_id', 'intake_section_revision', type_='foreignkey')
    op.create_foreign_key('fk_intake_section_revision_section_id', 'intake_section_revision', 'intakesection', ['intake_section_id'], ['id'], ondelete='SET NULL')
    op.alter_column('plandecisiontree', 'decision_tree_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('plandecisiontree_execution_id_fkey', 'plandecisiontree', type_='foreignkey')
    op.drop_constraint('plandecisiontree_plan_id_fkey', 'plandecisiontree', type_='foreignkey')
    op.drop_constraint('plandecisiontree_decision_tree_id_fkey', 'plandecisiontree', type_='foreignkey')
    op.create_foreign_key('plandecisiontree_execution_id_fkey', 'plandecisiontree', 'execution', ['execution_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('plandecisiontree_decision_tree_id_fkey', 'plandecisiontree', 'decisiontree', ['decision_tree_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('plandecisiontree_plan_id_fkey', 'plandecisiontree', 'plan', ['plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # Set default intake_type for existing records
    op.execute("UPDATE intake SET intake_type = 'conversation' WHERE intake_type IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plandecisiontree_decision_tree_id_fkey', 'plandecisiontree', type_='foreignkey')
    op.drop_constraint('plandecisiontree_plan_id_fkey', 'plandecisiontree', type_='foreignkey')
    op.drop_constraint('plandecisiontree_execution_id_fkey', 'plandecisiontree', type_='foreignkey')
    op.create_foreign_key('plandecisiontree_decision_tree_id_fkey', 'plandecisiontree', 'decisiontree', ['decision_tree_id'], ['id'])
    op.create_foreign_key('plandecisiontree_plan_id_fkey', 'plandecisiontree', 'plan', ['plan_id'], ['id'])
    op.create_foreign_key('plandecisiontree_execution_id_fkey', 'plandecisiontree', 'execution', ['execution_id'], ['id'])
    op.alter_column('plandecisiontree', 'decision_tree_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('fk_intake_section_revision_section_id', 'intake_section_revision', type_='foreignkey')
    op.create_foreign_key('fk_intake_section_revision_section_id', 'intake_section_revision', 'intakesection', ['intake_section_id'], ['id'], ondelete='CASCADE')
    op.alter_column('intake_section_revision', 'intake_section_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('intake', 'intake_type')
    op.drop_constraint('clientintakesection_intake_section_id_fkey', 'clientintakesection', type_='foreignkey')
    op.drop_constraint('clientintakesection_intake_id_fkey', 'clientintakesection', type_='foreignkey')
    op.create_foreign_key('clientintakesection_intake_section_id_fkey', 'clientintakesection', 'intakesection', ['intake_section_id'], ['id'])
    op.create_foreign_key('clientintakesection_intake_id_fkey', 'clientintakesection', 'intake', ['intake_id'], ['id'])
    op.alter_column('clientintakesection', 'intake_section_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('clientintakesection', 'intake_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('assessmentrevisionlink_assessment_tree_revision_id_fkey', 'assessmentrevisionlink', type_='foreignkey')
    op.drop_constraint('assessmentrevisionlink_assessment_id_fkey', 'assessmentrevisionlink', type_='foreignkey')
    op.create_foreign_key('assessmentrevisionlink_assessment_tree_revision_id_fkey', 'assessmentrevisionlink', 'assessmenttreerevision', ['assessment_tree_revision_id'], ['id'])
    op.create_foreign_key('assessmentrevisionlink_assessment_id_fkey', 'assessmentrevisionlink', 'assessment', ['assessment_id'], ['id'])
    op.drop_table('recording_chunk')
    op.drop_table('recording_session')
    # ### end Alembic commands ###

    # Drop the enum types
    recording_status_enum.drop(op.get_bind())
    intake_type_enum.drop(op.get_bind())
