"""fix notify ?

Revision ID: 5866d6491010
Revises: 5131a8c909b9
Create Date: 2025-08-26 12:24:38.961200

"""
from typing import Sequence, Union
from sqlmodel import SQLModel

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5866d6491010'
down_revision: Union[str, None] = '5131a8c909b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column if it exists -- yes it will reset the whole column, it's just an indicator whether the regen popup should be open
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('plangeneration')]

    if 'regeneration_notify' in columns:
        op.drop_column('plangeneration', 'regeneration_notify')
    # Add the column with the specified parameters
    op.add_column('plangeneration', sa.Column('regeneration_notify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('plangeneration')]

    if 'regeneration_notify' in columns:
        op.drop_column('plangeneration', 'regeneration_notify')
    # ### end Alembic commands ###
