"""plan generation execution status

Revision ID: 5f8f80b25df1
Revises: 768249737e1a
Create Date: 2024-10-11 18:54:33.861319

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8f80b25df1'
down_revision: Union[str, None] = '768249737e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('execution_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'plangeneration', 'execution', ['execution_id'], ['id'])
    op.drop_column('plangeneration', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'plangeneration', type_='foreignkey')
    op.drop_column('plangeneration', 'execution_id')
    # ### end Alembic commands ###
