"""Add deepgram transcription model

Revision ID: 60ba1d77289e
Revises: 2314f2d12fd6
Create Date: 2025-12-10 12:00:11.052187

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ba1d77289e'
down_revision: Union[str, None] = '2314f2d12fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording_session', sa.Column('deepgram_request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording_session', 'deepgram_request_id')
    # ### end Alembic commands ###
