"""plan_gen_default_status

Revision ID: 631222ca3d52
Revises: 340efacf06b8
Create Date: 2024-10-04 08:23:40.246843

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '631222ca3d52'
down_revision: Union[str, None] = '340efacf06b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decisiontree_id', table_name='decisiontree')
    op.drop_index('ix_decisiontreerevision_id', table_name='decisiontreerevision')
    op.alter_column('planasset', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('planasset', 'file_blob',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planasset', 'file_blob',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('planasset', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_decisiontreerevision_id', 'decisiontreerevision', ['id'], unique=True)
    op.create_index('ix_decisiontree_id', 'decisiontree', ['id'], unique=True)
    # ### end Alembic commands ###
