"""plan.oms_doc_id

Revision ID: 6d4a11c0fbd0
Revises: 8840de05d404
Create Date: 2024-10-18 18:09:18.427508

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4a11c0fbd0'
down_revision: Union[str, None] = '8840de05d404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('oms_doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'oms_doc_id')
    # ### end Alembic commands ###
