"""add_assessment_and_output_configs

Revision ID: 6f1b3d5fd07f
Revises: 9505eb3cd3a3
Create Date: 2025-10-16 14:44:57.482578

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1b3d5fd07f'
down_revision: Union[str, None] = '9505eb3cd3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessmentconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config_yaml', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_code', 'code', 'version', name='unique_assessment_version')
    )
    op.create_index('idx_assessment_config_state_active', 'assessmentconfig', ['state_code', 'is_active'], unique=False)
    op.create_table('outputconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('output_type', sa.Enum('intake_summary', 'action_plan', name='output_type_enum'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config_yaml', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='unique_output_version')
    )
    op.add_column('intake', sa.Column('assessment_config_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_intake_assessment_config_id'), 'intake', ['assessment_config_id'], unique=False)
    op.create_foreign_key('intake_assessment_config_id_fkey', 'intake', 'assessmentconfig', ['assessment_config_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('intake_assessment_config_id_fkey', 'intake', type_='foreignkey')
    op.drop_index(op.f('ix_intake_assessment_config_id'), table_name='intake')
    op.drop_column('intake', 'assessment_config_id')
    op.drop_table('outputconfig')
    op.drop_index('idx_assessment_config_state_active', table_name='assessmentconfig')
    op.drop_table('assessmentconfig')
    # Drop enum types
    op.execute('DROP TYPE IF EXISTS output_type_enum')
    # ### end Alembic commands ###
