"""update_external_api_in_config_outputs_files

Revision ID: 746b7d9a6c36
Revises: d8daa5378d45
Create Date: 2025-12-24 09:23:58.466795

"""
from pathlib import Path
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746b7d9a6c36'
down_revision: Union[str, None] = 'ec8bcb2f320a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    yaml_path = (
            Path(__file__).parent
            / "../../app/core/data_config/output_configs/plan-default-v0.yaml"
    )

    with open(yaml_path, "r") as f:
        yaml_content = f.read()

    # Escape single quotes for SQL
    yaml_content_escaped = yaml_content.replace("'", "''")

    # Update existing plandefault v0 config
    op.execute(
        f"""
            UPDATE outputconfig
            SET
                config_yaml = '{yaml_content_escaped}',
                updated_at = NOW()
            WHERE
                code = 'plandefault'
                AND version = 0
            """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
