"""add external chat messages to intake

Revision ID: 75b5ecb577d9
Revises: 9505eb3cd3a3
Create Date: 2025-10-21 17:36:38.183948

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b5ecb577d9'
down_revision: Union[str, None] = '9505eb3cd3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake', sa.Column('external_chat_messages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake', 'external_chat_messages')
    # ### end Alembic commands ###
