"""plan decision tree and execution

Revision ID: 768249737e1a
Revises: 3a3caf44e9a4
Create Date: 2024-10-10 19:08:43.856615

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768249737e1a'
down_revision: Union[str, None] = '3a3caf44e9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('table_entity_id', sa.Uuid(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plandecisiontree',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('decision_tree_id', sa.Uuid(), nullable=False),
    sa.Column('annotations', sa.JSON(), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('run_statements', sa.JSON(), nullable=True),
    sa.Column('run_steps', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['decision_tree_id'], ['decisiontree.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'decision_tree_id', name='unique_plan_decision_tree')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plandecisiontree')
    op.drop_table('execution')
    # ### end Alembic commands ###
