"""added plan type differentiator

Revision ID: 84f38fb01864
Revises: befcc1258e4e
Create Date: 2025-01-15 12:52:45.400217

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f38fb01864'
down_revision: Union[str, None] = 'befcc1258e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), server_default='live', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'type')
    # ### end Alembic commands ###
