"""plan create execution

Revision ID: 8840de05d404
Revises: 5f8f80b25df1
Create Date: 2024-10-15 16:46:12.106912

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8840de05d404'
down_revision: Union[str, None] = '5f8f80b25df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('create_execution_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'plan', 'execution', ['create_execution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan', type_='foreignkey')
    op.drop_column('plan', 'create_execution_id')
    # ### end Alembic commands ###
