"""add_external_to_intake_type_enum

Revision ID: 8fe8527ba3ca
Revises: 75b5ecb577d9
Create Date: 2025-10-22 08:00:12.433998

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe8527ba3ca'
down_revision: Union[str, None] = '75b5ecb577d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE intake_type_enum ADD VALUE IF NOT EXISTS 'external'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
