"""intake survey

Revision ID: 9505eb3cd3a3
Revises: c37f9a4f14fc
Create Date: 2025-10-03 10:53:29.112235

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9505eb3cd3a3'
down_revision: Union[str, None] = 'c37f9a4f14fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_survey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('intake_id', sa.Uuid(), nullable=False),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('questions_confusing', sa.Enum('NO', 'SOME', 'MOST_ALL', name='questionsconfusing'), nullable=True),
    sa.Column('preferred_method', sa.Enum('CHATBOT', 'VOICE', 'PERSON', 'OTHER', name='preferredmethod'), nullable=True),
    sa.Column('method_other', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('additional_feedback', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intake_survey')
    # ### end Alembic commands ###
