"""add_intake_id_to_assessment

Revision ID: 95ab1e381a66
Revises: e02ffa58da88
Create Date: 2025-03-20 14:29:06.454134

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ab1e381a66'
down_revision: Union[str, None] = 'e02ffa58da88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('intake_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'assessment', 'intake', ['intake_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assessment_intake_id_fkey', 'assessment', type_='foreignkey')
    op.drop_column('assessment', 'intake_id')
    # ### end Alembic commands ###
