"""add_client_address_collection

Revision ID: 97d2190210b2
Revises: 1d5a4a5adae8
Create Date: 2025-06-19 16:54:28.078372

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d2190210b2'
down_revision: Union[str, None] = '1d5a4a5adae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_address',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('intake_id', sa.Uuid(), nullable=False),
    sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('fk_intake_section_revision_section_id', 'intake_section_revision', type_='foreignkey')
    op.create_foreign_key(None, 'intake_section_revision', 'intakesection', ['intake_section_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_intake_section_current_revision', 'intakesection', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_intake_section_current_revision', 'intakesection', 'intake_section_revision', ['current_revision_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'intake_section_revision', type_='foreignkey')
    op.create_foreign_key('fk_intake_section_revision_section_id', 'intake_section_revision', 'intakesection', ['intake_section_id'], ['id'])
    op.drop_table('client_address')
    # ### end Alembic commands ###
