"""add_all_intake_tables

Revision ID: 9d306b6db61a
Revises: dc8d8b99b62e
Create Date: 2025-03-12 08:55:31.494972

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d306b6db61a'
down_revision: Union[str, None] = 'dc8d8b99b62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('created', 'paused', 'in_progress', 'error', 'review', 'completed', name='intake_status_enum'), nullable=False),
    sa.Column('current_section', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakesection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientintakesection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('intake_id', sa.Uuid(), nullable=False),
    sa.Column('intake_section_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('completion_status', sa.Enum('not_started', 'in_progress', 'completed', 'unclear', name='completion_status_enum'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.id'], ),
    sa.ForeignKeyConstraint(['intake_section_id'], ['intakesection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakemessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('intake_id', sa.Uuid(), nullable=False),
    sa.Column('from_role', sa.Enum('client', 'caseworker', name='intake_message_role_enum'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_message_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['intakemessage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intakemessage')
    op.drop_table('clientintakesection')
    op.drop_table('intakesection')
    op.drop_table('intake')
    # Drop enum types
    op.execute('DROP TYPE IF EXISTS intake_message_role_enum')
    op.execute('DROP TYPE IF EXISTS completion_status_enum')
    op.execute('DROP TYPE IF EXISTS intake_status_enum')
    # ### end Alembic commands ###
