"""add_resources_associations_map_to_plan_generation

Revision ID: a2950cdeccb6
Revises: 2edc3407cdb2
Create Date: 2026-04-02 14:13:46.141361

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2950cdeccb6'
down_revision: Union[str, None] = '2edc3407cdb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('resources_associations_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plangeneration', 'resources_associations_map')
    # ### end Alembic commands ###
