"""add seen_item table

Revision ID: a58ccb98f2ea
Revises: 69a7439e23d5
Create Date: 2026-05-08 14:32:15.449246

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58ccb98f2ea'
down_revision: Union[str, None] = 'b9c8d7e6f5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seen_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seen_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intake_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.Enum('intake_conversation', 'intake_summary', 'action_plan', name='seenitemtype'), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seen_by', 'item_type', 'item_id', name='uq_seen_item_admin_type_item')
    )
    op.create_index('ix_seen_item_admin_intake', 'seen_item', ['seen_by', 'intake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seen_item_admin_intake', table_name='seen_item')
    op.drop_table('seen_item')
    # Dropping the table doesn't drop the enum type in Postgres; drop it
    # explicitly so re-running upgrade doesn't fail with DuplicateObjectError.
    op.execute("DROP TYPE IF EXISTS seenitemtype")
    # ### end Alembic commands ###
