"""Add internal_access to intake

Revision ID: b920cd908db2
Revises: 312dcc5dfe92
Create Date: 2025-05-21 09:57:24.583607

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b920cd908db2'
down_revision: Union[str, None] = '312dcc5dfe92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
     # ### commands auto generated by Alembic - please adjust! ###
     op.add_column('intake', sa.Column('internal_access', sa.Boolean(), nullable=True))
     # ### end Alembic commands ###


def downgrade() -> None:
     # ### commands auto generated by Alembic - please adjust! ###
     op.drop_column('intake', 'internal_access')
     # ### end Alembic commands ###
