"""add_client_info

Revision ID: befcc1258e4e
Revises: 35af5feee67b
Create Date: 2024-11-14 16:18:30.039083

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'befcc1258e4e'
down_revision: Union[str, None] = '35af5feee67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('client_extracted_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'client_extracted_info')
    # ### end Alembic commands ###
