"""remove_parent_message

Revision ID: c2110adc880e
Revises: 0d0e9f7b252d
Create Date: 2025-04-04 11:21:10.711604

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2110adc880e'
down_revision: Union[str, None] = '05cc76adf335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('intakemessage_parent_message_id_fkey', 'intakemessage', type_='foreignkey')
    op.drop_column('intakemessage', 'parent_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intakemessage', sa.Column('parent_message_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('intakemessage_parent_message_id_fkey', 'intakemessage', 'intakemessage', ['parent_message_id'], ['id'])
    # ### end Alembic commands ###
