"""Adding duration to session

Revision ID: c37f9a4f14fc
Revises: 464d419329c5
Create Date: 2025-09-30 16:37:07.357208

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37f9a4f14fc'
down_revision: Union[str, None] = '464d419329c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording_session', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording_session', 'duration')
    # ### end Alembic commands ###
