"""Add transcription validations

Revision ID: d3e5ba0cd6c9
Revises: 44a6522adfe5
Create Date: 2026-01-15 11:25:57.623143

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e5ba0cd6c9'
down_revision: Union[str, None] = '44a6522adfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording_session', sa.Column('validation_word_count', sa.Boolean(), nullable=False))
    op.add_column('recording_session', sa.Column('validation_no_prompt_injection', sa.Boolean(), nullable=False))
    op.add_column('recording_session', sa.Column('validation_diarization', sa.Boolean(), nullable=False))
    op.add_column('recording_session', sa.Column('validation_minimum_duration', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording_session', 'validation_minimum_duration')
    op.drop_column('recording_session', 'validation_diarization')
    op.drop_column('recording_session', 'validation_no_prompt_injection')
    op.drop_column('recording_session', 'validation_word_count')
    # ### end Alembic commands ###
