"""adds_assessments

Revision ID: dc8d8b99b62e
Revises: 3163b8f46945
Create Date: 2025-02-12 18:59:12.983242

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8d8b99b62e'
down_revision: Union[str, None] = '3163b8f46945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('runs_steps', sa.JSON(), nullable=True),
    sa.Column('misses_counts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessmentrevisionlink',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_tree_revision_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['assessment_tree_revision_id'], ['assessmenttreerevision.id'], ),
    sa.PrimaryKeyConstraint('assessment_id', 'assessment_tree_revision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessmentrevisionlink')
    op.drop_table('assessment')
    # ### end Alembic commands ###
