"""plangeneration.gen_data_json

Revision ID: dd34ed9ea02a
Revises: 1a96d0bdd3e9
Create Date: 2024-10-23 10:39:34.656700

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd34ed9ea02a'
down_revision: Union[str, None] = '1a96d0bdd3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('gen_data_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plangeneration', 'gen_data_json')
    # ### end Alembic commands ###
