"""add required_information field to intake_section

Revision ID: e00a16727f8b
Revises: 16bf98f18f3c
Create Date: 2025-06-06 13:03:36.990110

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00a16727f8b'
down_revision: Union[str, None] = '16bf98f18f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('intakesection', sa.Column('required_information', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Update existing records to move description content to required_information
    op.execute("""
        UPDATE intakesection
        SET required_information = description
        WHERE required_information IS NULL
    """)

    # Now make the column not nullable
    op.alter_column('intakesection', 'required_information', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intakesection', 'required_information')
    # ### end Alembic commands ###
