"""add_resource_content_to_plan_generation

Revision ID: e02ffa58da88
Revises: 9d306b6db61a
Create Date: 2025-03-11 17:25:38.236816

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02ffa58da88'
down_revision: Union[str, None] = '9d306b6db61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('resource_to_add_content', sa.JSON(), nullable=True))
    op.drop_column('plangeneration', 'resource_to_add_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('resource_to_add_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('plangeneration', 'resource_to_add_content')
    # ### end Alembic commands ###
