"""add PlanGeneration.force_generation

Revision ID: eb68d94e870b
Revises: 97d2190210b2
Create Date: 2025-07-09 16:59:07.594892

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb68d94e870b'
down_revision: Union[str, None] = '97d2190210b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plangeneration', sa.Column('force_generation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plangeneration', 'force_generation')
    # ### end Alembic commands ###
