"""intake_section_assessment_rename

Revision ID: ec7bf28d89c8
Revises: d2d038f77af4
Create Date: 2025-09-16 17:39:54.726046

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7bf28d89c8'
down_revision: Union[str, None] = 'd2d038f77af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intakesection', sa.Column('intake_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('unique_title_assessment_type', 'intakesection', type_='unique')
    op.create_unique_constraint('unique_title_intake_name', 'intakesection', ['title', 'intake_name'])
    op.drop_column('intakesection', 'assessment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intakesection', sa.Column('assessment_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('unique_title_intake_name', 'intakesection', type_='unique')
    op.create_unique_constraint('unique_title_assessment_type', 'intakesection', ['title', 'assessment_type'])
    op.drop_column('intakesection', 'intake_name')
    # ### end Alembic commands ###
