"""recording chunk update

Revision ID: f3142bcfd92e
Revises: ec7bf28d89c8
Create Date: 2025-09-19 15:51:55.782190

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3142bcfd92e'
down_revision: Union[str, None] = 'ec7bf28d89c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording_chunk', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    op.drop_constraint('uq_session_chunk', 'recording_chunk', type_='unique')
    op.create_unique_constraint('uq_session_timestamp', 'recording_chunk', ['session_id', 'timestamp'])
    op.add_column('recording_session', sa.Column('last_chunk_timestamp', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording_session', 'last_chunk_timestamp')
    op.drop_constraint('uq_session_timestamp', 'recording_chunk', type_='unique')
    op.create_unique_constraint('uq_session_chunk', 'recording_chunk', ['session_id', 'chunk_index'])
    op.drop_column('recording_chunk', 'timestamp')
    # ### end Alembic commands ###
