"""add_cascade_deletes_for_all_foreign_keys

Revision ID: f714aeffa418
Revises: e4f5a6b7c8d9
Create Date: 2026-02-06 18:52:20.874376

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f714aeffa418'
down_revision: Union[str, None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assessment_intake_id_fkey', 'assessment', type_='foreignkey')
    op.create_foreign_key('assessment_intake_id_fkey', 'assessment', 'intake', ['intake_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('plan_intake_id_fkey', 'plan', type_='foreignkey')
    op.create_foreign_key('plan_intake_id_fkey', 'plan', 'intake', ['intake_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('planasset_plan_id_fkey', 'planasset', type_='foreignkey')
    op.create_foreign_key('planasset_plan_id_fkey', 'planasset', 'plan', ['plan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('plangeneration_plan_id_fkey', 'plangeneration', type_='foreignkey')
    op.create_foreign_key('plangeneration_plan_id_fkey', 'plangeneration', 'plan', ['plan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recording_chunk_session_id_fkey', 'recording_chunk', type_='foreignkey')
    op.create_foreign_key('recording_chunk_session_id_fkey', 'recording_chunk', 'recording_session', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recording_chunk_session_id_fkey', 'recording_chunk', type_='foreignkey')
    op.create_foreign_key('recording_chunk_session_id_fkey', 'recording_chunk', 'recording_session', ['session_id'], ['id'])
    op.drop_constraint('plangeneration_plan_id_fkey', 'plangeneration', type_='foreignkey')
    op.create_foreign_key('plangeneration_plan_id_fkey', 'plangeneration', 'plan', ['plan_id'], ['id'])
    op.drop_constraint('planasset_plan_id_fkey', 'planasset', type_='foreignkey')
    op.create_foreign_key('planasset_plan_id_fkey', 'planasset', 'plan', ['plan_id'], ['id'])
    op.drop_constraint('plan_intake_id_fkey', 'plan', type_='foreignkey')
    op.create_foreign_key('plan_intake_id_fkey', 'plan', 'intake', ['intake_id'], ['id'])
    op.drop_constraint('assessment_intake_id_fkey', 'assessment', type_='foreignkey')
    op.create_foreign_key('assessment_intake_id_fkey', 'assessment', 'intake', ['intake_id'], ['id'])
    # ### end Alembic commands ###
