/*
  Warnings:

  - The primary key for the `Person` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to drop the column `externalId` on the `Person` table. All the data in the column will be lost.
  - Added the required column `stableExternalId` to the `Person` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE "MessageSeries" DROP CONSTRAINT "MessageSeries_personExternalId_fkey";

-- DropForeignKey
ALTER TABLE "_GroupToPerson" DROP CONSTRAINT "_GroupToPerson_B_fkey";

-- AUTOGENERATED STEP:  AlterTable
-- ALTER TABLE "Person" DROP CONSTRAINT "Person_pkey",
-- DROP COLUMN "externalId",
-- ADD COLUMN     "stableExternalId" TEXT NOT NULL,
-- ADD CONSTRAINT "Person_pkey" PRIMARY KEY ("stableExternalId");

-- CUSTOM SQL:
ALTER TABLE "Person" DROP CONSTRAINT "Person_pkey";
ALTER TABLE "Person" ADD COLUMN "stableExternalId" TEXT;
UPDATE "Person" SET "stableExternalId" = "externalId";
-- Enforce NOT NULL on the new column
-- This will succeed now that all rows have a value
ALTER TABLE "Person" ALTER COLUMN "stableExternalId" SET NOT NULL;
ALTER TABLE "Person" ADD CONSTRAINT "Person_pkey" PRIMARY KEY ("stableExternalId");
ALTER TABLE "Person" DROP COLUMN "externalId";

-- AddForeignKey
ALTER TABLE "MessageSeries" ADD CONSTRAINT "MessageSeries_personExternalId_fkey" FOREIGN KEY ("personExternalId") REFERENCES "Person"("stableExternalId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_GroupToPerson" ADD CONSTRAINT "_GroupToPerson_B_fkey" FOREIGN KEY ("B") REFERENCES "Person"("stableExternalId") ON DELETE CASCADE ON UPDATE CASCADE;
