import uuid
from pathlib import Path

import inquirer
import orjson
from langchain_core.document_loaders import LangSmithLoader
from langsmith import Client
from langsmith.evaluation import aevaluate
from pydantic import BaseModel

from app.core.config import settings
from app.core.data_config.output_configs.loader import OutputFileLoader
from app.manage.base import cli
from app.utils.llm_agent_gen_plan import LLMAgentGenerate

from .markdown_evals import (
    actionable,
    addressed_to_client,
    clarity,
    no_judgments,
    structure,
    timeline,
    tone,
)

langsmith_client = Client(
    api_key=settings.LANGCHAIN_API_KEY,
    api_url=settings.LANGCHAIN_ENDPOINT,
)


experiment_prefix_explanation = (
    "Experiment prefix: should represent the parameters of the current experiment\n"
    "and how it differs from others you might want to compare it against.\n"
    "If ignored, it will be two random words generated by langsmith."
)

experiment_prefix_question = inquirer.Text(
    "experiment_prefix",
    message="Experiment prefix (recommended)",
)


class EvaluationExample(BaseModel):
    """
    Everything we need to run the evaluation test.
    Matches the plan assets structure: messages, intake summary, assessment summary.
    """

    # Required fields
    client_id: str  # Unique identifier for the client
    messages: list[
        dict
    ]  # messages.json - intake conversation messages (array of message objects)
    summary: str  # summary.md - intake summary
    address: str
    # Optional plan assets and metadata
    assessment_summary: str | None = (
        None  # assessment_summary.md - risk assessment summary
    )
    decision_tree_statements: str | None = None  # Decision tree recommendations
    previous_sections: list[str] | None = None  # For testing regeneration scenarios


async def upload_dataset(dataset_name: str, path: Path):
    """
    Upload a dataset to LangSmith from a folder of JSON files.
    Each JSON file should contain messages, summary, and optionally assessment_summary.
    """
    # Convert to Path object if string is passed, trim whitespace
    if isinstance(path, str):
        path = Path(path.strip())
    else:
        path = Path(path)

    # Check that the path is a valid directory
    if not path.exists():
        raise ValueError(f"Path {path} does not exist")
    if not path.is_dir():
        raise ValueError(f"Path {path} is not a directory")

    # Find all JSON files in the directory
    json_files = list(path.glob("*.json"))
    if not json_files:
        raise ValueError(f"No JSON files found in {path}")

    print(f"Found {len(json_files)} JSON files in {path}")

    # Load and validate each file as EvaluationExample
    examples = []
    for json_file in json_files:
        try:
            with open(json_file, "r") as f:
                data = orjson.loads(f.read())

            # Validate as EvaluationExample - Pydantic will do its job
            example = EvaluationExample(**data)

            # Store for LangSmith
            examples.append(
                {
                    "inputs": example.model_dump(),
                    "outputs": None,  # We don't have expected outputs for generation tasks
                }
            )

        except Exception as e:
            print(f"Warning: Failed to load {json_file}: {e}")
            continue

    if not examples:
        raise ValueError("No valid examples could be loaded")

    print(f"Validated {len(examples)} examples")

    # Create dataset in LangSmith
    dataset = langsmith_client.create_dataset(dataset_name=dataset_name)
    print(f"Created dataset '{dataset_name}' with id {dataset.id}")

    # Create examples in the dataset
    langsmith_client.create_examples(
        inputs=[ex["inputs"] for ex in examples],
        outputs=[ex["outputs"] for ex in examples],
        dataset_id=dataset.id,
    )

    print(f"Successfully uploaded {len(examples)} examples to dataset '{dataset_name}'")

    return examples


async def initialize_existing(dataset_name: str):
    """
    Load an existing dataset from LangSmith and validate examples.
    Returns a list of validated EvaluationExample objects.
    """
    loader = LangSmithLoader(dataset_name=dataset_name, client=langsmith_client)
    dataset = await loader.aload()
    print(f"Fetched {len(dataset)} examples from dataset '{dataset_name}'")

    # Validate examples with EvaluationExample model - Pydantic will do its job
    examples = []
    for doc in dataset:
        try:
            # Extract the inputs from the document
            if hasattr(doc, "inputs"):
                data = doc.inputs
            elif hasattr(doc, "metadata"):
                data = doc.metadata
            else:
                print("Warning: Document has no inputs or metadata")
                continue

            # Validate as EvaluationExample
            example = EvaluationExample(**data)
            examples.append(example)

        except Exception as e:
            print(f"Warning: Failed to validate example: {e}")
            continue

    print(f"Validated {len(examples)} examples")
    return examples


@cli.command()
async def evaluate(output_config_file: str = "plan-default-v0.yaml"):
    """
    Launches the evaluation process for the generation of action plans interactively asking for user input

    Args:
        output_config_file: Action plan output config YAML filename (default: "plan-default-v0.yaml", None for defaults)
    """
    if not settings.LANGCHAIN_API_KEY:
        raise ValueError("Experiments are run on Langsmith, please provide an API key")

    print(f"Loading action plan config: {output_config_file}")
    yaml_content = OutputFileLoader.read_file_content(output_config_file)
    action_plan_config = OutputFileLoader.validate_yaml_content(yaml_content)
    print(
        f"Loaded config: {action_plan_config.metadata.code} v{action_plan_config.metadata.version}"
    )

    print(
        "\nWhat evaluation do you want to run?\n- Default runs a predefined set of a few examples\n- Existing will let you pick from available datasets\n- New will let you create a new dataset from a folder\n"
    )

    dataset_choice_question = inquirer.List(
        "dataset_choice",
        message="Your choice",
        choices=["Default", "Existing", "New"],
    )

    dataset_choice_answer = inquirer.prompt([dataset_choice_question])
    if dataset_choice_answer is None:
        raise ValueError("No input provided for dataset choice.")

    dataset_choice = dataset_choice_answer["dataset_choice"]

    match dataset_choice:
        case "Default":
            dataset_name = "plan-generation-dev"
            experiment_prefix = None
            await initialize_existing(dataset_name)

        case "Existing":
            datasets = langsmith_client.list_datasets()
            if not datasets:
                raise ValueError("No dataset found")
            dataset_selection_question = inquirer.List(
                "dataset_selection",
                message="Please select a dataset",
                choices=[dataset.name for dataset in datasets],
            )
            print(experiment_prefix_explanation)
            print("\n")

            answers = inquirer.prompt(
                [dataset_selection_question, experiment_prefix_question]
            )
            if answers is None:
                raise ValueError("No input provided for dataset selection.")

            dataset_name = answers["dataset_selection"]
            experiment_prefix = answers["experiment_prefix"]

            await initialize_existing(dataset_name)

        case "New":
            print(
                "Path: Provide a folder containing one JSON file per example.\nYou can find examples in data/examples/default_eval\n"
            )
            print(experiment_prefix_explanation)
            print("\n")
            experiment_name_question = inquirer.Text(
                "dataset_name", "Enter a unique name for your dataset"
            )
            path_question = inquirer.Path(
                "dataset_path",
                message="Path",
                default=None,
            )
            answers = inquirer.prompt(
                [path_question, experiment_name_question, experiment_prefix_question]
            )
            if answers is None:
                raise ValueError("No input provided for new dataset creation.")

            dataset_name = answers["dataset_name"]
            dataset_path = answers["dataset_path"]
            experiment_prefix = answers["experiment_prefix"]

            while langsmith_client.has_dataset(dataset_name=dataset_name):
                dataset_name_res = inquirer.prompt(
                    [
                        inquirer.Text(
                            "dataset_name", "This dataset already exists, try again"
                        )
                    ]
                )
                if dataset_name_res is None:
                    raise ValueError("Input needed to change dataset name.")
                dataset_name = dataset_name_res["dataset_name"]

            while not Path(dataset_path).exists:
                dataset_path_res = inquirer.prompt(
                    [
                        inquirer.Path(
                            "dataset_path", message="Folder not found, try again"
                        )
                    ]
                )
                if dataset_path_res is None:
                    raise ValueError("Input required for valid dataset path.")
                dataset_path = dataset_path_res["dataset_path"]

            await upload_dataset(dataset_name, dataset_path)

    async def generate_example_output(example: dict | EvaluationExample):
        """
        Generate action plan output from an evaluation example.
        Mimics the data construction from get_client_background_data and _generate_new_action_plan.
        """
        # Convert dict to EvaluationExample if needed (aevaluate passes dicts)
        if isinstance(example, dict):
            example = EvaluationExample(**example)

        # Build client_data string (mimicking get_client_background_data in action_plan.py)
        client_data = ""

        # Add intake messages
        if example.messages:
            from app.tasks.action_plan import render_intake_messages

            messages_json = orjson.dumps(example.messages).decode()
            messages_text = render_intake_messages(messages_json)
            client_data += f"# Client intake messages\n\n{messages_text}\n\n"

        # Add intake summary
        if example.summary:
            client_data += f"# Client intake summary\n\n{example.summary}\n\n"

        # Add assessment summary if available
        if example.assessment_summary:
            client_data += f"# Client risk summary\n\n{example.assessment_summary}\n\n"

        if not client_data:
            raise ValueError("No client data in example")

        # Use provided values or defaults
        decision_tree_statements = example.decision_tree_statements or ""
        previous_sections = example.previous_sections
        address = example.address

        # Generate unique thread_id for this evaluation
        thread_id = uuid.uuid4()

        # Create the agent and generate the action plan
        agent = LLMAgentGenerate(
            client_data=client_data,
            decision_tree_statements=decision_tree_statements,
            client_address=address,
            previous_sections=previous_sections,
            thread_id=thread_id,
            action_plan_config=action_plan_config,
        )

        action_plan = await agent.generate()

        return {
            "markdown": action_plan.action_plan,
            "gen_data": action_plan.messages,
            "resources": action_plan.suggested_resources,
        }

    results = await aevaluate(
        generate_example_output,
        data=dataset_name,
        evaluators=[
            addressed_to_client,
            clarity,
            actionable,
            structure,
            tone,
            timeline,
            no_judgments,
        ],
        client=langsmith_client,
        experiment_prefix=experiment_prefix,
    )

    # Save results next to examples folder in data/results
    dataset_dir = (
        Path(__file__).parent.parent.parent.parent / "data" / "results" / dataset_name
    )
    dataset_dir.mkdir(parents=True, exist_ok=True)

    results.to_pandas().to_pickle(dataset_dir / f"{results.experiment_name}.pkl")

    # Save markdown results for each client in a folder
    markdown_dir = dataset_dir / f"{results.experiment_name}_markdown"
    markdown_dir.mkdir(parents=True, exist_ok=True)

    df = results.to_pandas()
    for idx, row in df.iterrows():
        client_id = row.get("inputs.client_id", f"client_{idx}")
        markdown_content = row.get("outputs.markdown", "")
        if markdown_content:
            markdown_file = markdown_dir / f"{client_id}.md"
            markdown_file.write_text(markdown_content, encoding="utf-8")

    print(f"\nMarkdown files saved to: {markdown_dir}")
    print(results.to_pandas())
