# ### TODO Adapt eval framework to new client and intake ###


# import uuid
# from pathlib import Path
# from typing import TypedDict

# import inquirer
# import orjson
# from langchain_core.document_loaders import LangSmithLoader
# from langsmith import Client
# from langsmith.evaluation import aevaluate
# from langsmith.schemas import Example

# from app.core.config import settings
# from app.manage.base import cli
# from app.manage.create_plan import _create_plan
# from app.manage.evaluate.evaluation_context import EvaluationExampleFile


# from .markdown_evals import (
#     actionable,
#     addressed_to_client,
#     clarity,
#     no_judgments,
#     structure,
#     timeline,
#     tone,
# )

# langsmith_client = Client(
#     api_key=settings.LANGCHAIN_API_KEY,
#     api_url=settings.LANGCHAIN_ENDPOINT,
# )


# class ExampleIdentifiers(TypedDict):
#     client_id: str


# experiment_prefix_explanation = (
#     "Experiment prefix: should represent the parameters of the current experiment\n"
#     "and how it differs from others you might want to compare it against.\n"
#     "If ignored, it will be two random words generated by langsmith."
# )

# experiment_prefix_question = inquirer.Text(
#     "experiment_prefix",
#     message="Experiment prefix (recommended)",
# )


# async def create_dataset(dataset_name: str, data_identifiers: list[str] | None):
#     clientdata = ClientData()
#     await clientdata.load_cache()

#     if data_identifiers:
#         inputs = []
#         for id in data_identifiers:
#             input = {"client_id": id}
#             oms_data = clientdata.find_by_doc_id(id)
#             input["oms_data"] = oms_data and oms_data.json() or ""
#             input["messages"] = await fabrk_fetch_intake_messages(id)
#             input["summary"] = await fabrk_fetch_intake_summary(id)
#             inputs.append(input)

#     else:
#         inputs = [
#             {"client_id": "133365a5-8425-48e1-bec4-334a46203540"},
#             {"client_id": "f40dac7b-969c-4ff1-92d2-ee101848bba5"},
#             {"client_id": "23d296a5-1171-40db-bf69-a5bed4efe084"},
#         ]
#         for input in inputs:
#             oms_data = clientdata.find_by_doc_id(input["client_id"])
#             input["oms_data"] = oms_data.json() if oms_data else ""
#             input["messages"] = await fabrk_fetch_intake_messages(input["client_id"])
#             input["summary"] = await fabrk_fetch_intake_summary(input["client_id"])

#     examples = [elmt for elmt in inputs if elmt is not None and elmt["messages"]]
#     if len(examples) > 0:
#         dataset = langsmith_client.create_dataset(dataset_name=dataset_name)
#         langsmith_client.create_examples(inputs=examples, dataset_id=dataset.id)
#     else:
#         raise ValueError("No examples found")


# async def create_and_initialize(dataset_name: str, dataset_path: str):
#     from app.manage.evaluate.evaluation_context import (
#         EvaluationContext,
#         EvaluationExample,
#         EvaluationExamples,
#     )

#     all_examples: EvaluationExamples = {}
#     for filename in Path(dataset_path).glob("*.json"):
#         example_data = orjson.loads(filename.read_text())

#         try:
#             example = EvaluationExampleFile.model_validate(example_data)
#             # To avoid collisions with real data, we prefix the fake identifiers
#             example_id = "eval_" + str(uuid.uuid4())
#             all_examples[example_id] = EvaluationExample(
#                 summary=example.summary,
#                 messages=example.messages,
#                 oms_data=ClientDataRecord.model_validate(example.oms_data),
#                 client_id=example_id,
#             )
#         except Exception as e:
#             print(f"Error parsing {filename}: {str(e)}")
#             continue

#     print("Loaded and validated dataset from provided path.")
#     EvaluationContext(all_examples)
#     print("Provided examples")

#     await create_dataset(dataset_name, list(all_examples.keys()))
#     print("Created Dataset")


# async def initialize_existing(dataset_name: str):
#     from app.manage.evaluate.evaluation_context import (
#         EvaluationContext,
#         EvaluationExample,
#         EvaluationExamples,
#     )

#     loader = LangSmithLoader(dataset_name=dataset_name, client=langsmith_client)
#     dataset = await loader.aload()
#     print("Fetched examples")
#     examples = [document.metadata["inputs"] for document in dataset]
#     parsed_examples = [
#         EvaluationExample(
#             client_id=example["client_id"],
#             oms_data=(example["oms_data"])
#             and ClientDataRecord.model_validate(orjson.loads(example["oms_data"]))
#             or None,
#             summary=example["summary"],
#             messages=example["messages"],
#         )
#         for example in examples
#     ]
#     print("Valiated examples")

#     evaluation_examples: EvaluationExamples = {
#         example.client_id: example for example in parsed_examples
#     }
#     EvaluationContext(evaluation_examples)
#     print("Provided examples")


# @cli.command()
# async def evaluate():
#     """
#     Launches the evaluation process for the generation of action plans interactively asking for user input
#     """
#     if not settings.LANGCHAIN_API_KEY:
#         raise ValueError("Experiments are run on Langsmith, please provide an API key")

#     print(
#         "\nWhat evaluation do you want to run?\n- Default runs a predefined set of a few examples\n- Existing will let you pick from available datasets\n- New will let you create a new dataset from a folder\n"
#     )

#     dataset_choice_question = inquirer.List(
#         "dataset_choice",
#         message="Your choice",
#         choices=["Default", "Existing", "New"],
#     )

#     dataset_choice_answer = inquirer.prompt([dataset_choice_question])
#     if dataset_choice_answer is None:
#         raise ValueError("No input provided for dataset choice.")

#     dataset_choice = dataset_choice_answer["dataset_choice"]

#     match dataset_choice:
#         case "Default":
#             dataset_name = "dev_recidiviz"
#             experiment_prefix = None
#             if not langsmith_client.has_dataset(dataset_name=dataset_name):
#                 await create_dataset(dataset_name, None)

#             await initialize_existing(dataset_name)

#         case "Existing":
#             datasets = langsmith_client.list_datasets()
#             if not datasets:
#                 raise ValueError("No dataset found")
#             dataset_selection_question = inquirer.List(
#                 "dataset_selection",
#                 message="Please select a dataset",
#                 choices=[dataset.name for dataset in datasets],
#             )
#             print(experiment_prefix_explanation)
#             print("\n")

#             answers = inquirer.prompt(
#                 [dataset_selection_question, experiment_prefix_question]
#             )
#             if answers is None:
#                 raise ValueError("No input provided for dataset selection.")

#             dataset_name = answers["dataset_selection"]
#             experiment_prefix = answers["experiment_prefix"]

#             await initialize_existing(dataset_name)

#         case "New":
#             print(
#                 "Path: Provide a folder containing one JSON file per example.\nYou can find an example in experiments/evaluation/inputs/biais_eval_concept\n"
#             )
#             print(experiment_prefix_explanation)
#             print("\n")
#             experiment_name_question = inquirer.Text(
#                 "dataset_name", "Enter a unique name for your dataset"
#             )
#             path_question = inquirer.Path(
#                 "dataset_path",
#                 message="Path",
#                 default=None,
#             )
#             answers = inquirer.prompt(
#                 [path_question, experiment_name_question, experiment_prefix_question]
#             )
#             if answers is None:
#                 raise ValueError("No input provided for new dataset creation.")

#             dataset_name = answers["dataset_name"]
#             dataset_path = answers["dataset_path"]
#             experiment_prefix = answers["experiment_prefix"]

#             while langsmith_client.has_dataset(dataset_name=dataset_name):
#                 dataset_name_res = inquirer.prompt(
#                     [
#                         inquirer.Text(
#                             "dataset_name", "This dataset already exists, try again"
#                         )
#                     ]
#                 )
#                 if dataset_name_res is None:
#                     raise ValueError("Input needed to change dataset name.")
#                 dataset_name = dataset_name_res["dataset_name"]

#             while not Path(dataset_path).exists:
#                 dataset_path_res = inquirer.prompt(
#                     [
#                         inquirer.Path(
#                             "dataset_path", message="Folder not found, try again"
#                         )
#                     ]
#                 )
#                 if dataset_path_res is None:
#                     raise ValueError("Input required for valid dataset path.")
#                 dataset_path = dataset_path_res["dataset_path"]

#             await create_and_initialize(dataset_name, dataset_path)

#     # experiments/evaluation/biais_eval_concept
#     # Todo mark plans as experimental so we can hide them/batch delete etc
#     async def generate_example_output(example: Example):
#         plan, latest_generation = await _create_plan(
#             client_id=example["client_id"],
#             force=True,
#             mark_eval=True,
#         )

#         return {
#             "markdown": latest_generation.markdown_result,
#             "gen_data": latest_generation.gen_data_json,
#         }

#     results = await aevaluate(
#         generate_example_output,
#         data=dataset_name,
#         evaluators=[
#             addressed_to_client,
#             clarity,
#             actionable,
#             structure,
#             tone,
#             timeline,
#             no_judgments,
#         ],
#         client=langsmith_client,
#         experiment_prefix=experiment_prefix,
#     )

#     dataset_dir = (
#         Path(__file__).parent.parent.parent.parent
#         / "experiments"
#         / "evaluation"
#         / "results"
#         / dataset_name
#     )
#     dataset_dir.mkdir(parents=True, exist_ok=True)

#     results.to_pandas().to_pickle(dataset_dir / f"{results.experiment_name}.pkl")

#     print(results.to_pandas())
