name: "Request: Question"
description: "File a request for a clarification on intended tool behavior or policy."
title: "[<UBN/P0/P1>][<US_XX>][<Product>]: "
labels: []
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request clarification on intended tool behavior or policy.
        Refer to [go/slas](https://docs.google.com/document/d/15oVaisNkKTbagTVhXjqqf_iE7YW6g1_Jq9k-s-UMWrc) to determine the proper priority, label, and assignees for this issue.
  - type: input
    id: product
    attributes:
      label: Product
      description: e.g. Workflows, Tasks, Supervisor Homepage, JII texts, JII facilities app, PSI, Vitals, Lantern, Spotlight
      placeholder: 
    validations:
      required: true
  - type: input
    id: states
    attributes:
      label: State(s)
      description: 
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: policy
    attributes:
      label: Policy question
      description: e.g. Do we exclude folks with past sex offenses on early discharge?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Please explain what instigated this question (e.g. Officer X thinks his clients should not be appearing as eligible)
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Checklists
      description: 
      options:
        - label: "Added label for Team: State Pod or Team: Polaris"
          required: false
        - label: "Added label for Region: US_XX (if applicable)"
          required: false
        - label: "Added the appropriate Project: label (Workflows, Insights, JII, PSI, Vitals, Lantern)"
          required: false