name: "[Request] Feature"
description: "File a request for a new feature or enhancement."
title: "[<UBN/P0/P1>][<US_XX>][<Product>]: "
labels: ["Type: Feature"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to make a feature request. 
        *Note*: If this is product feedback that should be triaged by a Polaris PM, fill out [go/product-feedback-form](https://www.notion.so/recidiviz/1737889f4d19801ebb91c4aeb6df4cce) instead of making a ticket!
        Refer to [go/slas](https://docs.google.com/document/d/15oVaisNkKTbagTVhXjqqf_iE7YW6g1_Jq9k-s-UMWrc) to determine the proper priority, label, and assignees for this issue.
  - type: input
    id: product
    attributes:
      label: Product
      description: e.g. Workflows, Tasks, Supervisor Homepage, JII texts, JII facilities app, PSI, Vitals, Lantern, Spotlight
      placeholder: 
    validations:
      required: true
  - type: input
    id: states
    attributes:
      label: Which states would this be for?
      description: 
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: users
    attributes:
      label: If this feature was requested by users, by which users and how many?
      description: Provide IDs of officer, client, and/or resident in go/github-pii, if applicable.
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature request
      description: e.g. Can we add clients in specialty court to Workflows tasks?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is an example of expected behavior?
      description: e.g. Client X would ideally appear as needing a home contact
    validations:
      required: true
  - type: textarea
    id: explain
    attributes:
      label: Explain why this feature is needed
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Checklists
      description: 
      options:
        - label: "Added label for Team: State Pod or Team: Polaris"
          required: false
        - label: "Added label for Region: US_XX (if applicable)"
          required: false
        - label: "Added the appropriate Project: label (Workflows, Insights, JII, PSI, Vitals, Lantern)"
          required: false