name: "[Request] Data pull"
description: "File a request for a data pull."
title: "[UBN/P0/P1][Request]: "
labels: []
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request a data pull.
        Refer to [go/slas](https://docs.google.com/document/d/15oVaisNkKTbagTVhXjqqf_iE7YW6g1_Jq9k-s-UMWrc) to determine the proper priority, label, and assignees for this issue.
  - type: input
    id: product
    attributes:
      label: Product
      description: e.g. Workflows, Tasks, Supervisor Homepage, JII texts, JII facilities app, PSI, Vitals, Lantern, Spotlight
      placeholder: 
    validations:
      required: true
  - type: input
    id: states
    attributes:
      label: Which states do we want data about?
      description: 
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: users
    attributes:
      label: If this data was requested by users, by which users and how many?
      description: Provide IDs of officer, client, and/or resident in go/github-pii, if applicable.
    validations:
      required: false
  - type: textarea
    id: describe
    attributes:
      label: Describe what data is needed
    validations:
      required: true
  - type: textarea
    id: explain
    attributes:
      label: Explain why this data is needed
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Checklists
      description: 
      options:
        - label: "Added label for Team: State Pod or Team: Polaris"
          required: false
        - label: "Added label for Region: US_XX (if applicable)"
          required: false
        - label: "Added the appropriate Project: label (Workflows, Insights, JII, PSI, Vitals, Lantern)"
          required: false