// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2025 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

import { relativeFixtureDate } from "../../../utils/zod";
import {
  RawResidentCommon,
  residentCommonSchema,
} from "../residentCommonSchema";
import {
  RawWorkflowsResidentRecord,
  workflowsResidentRecordSchema,
} from "../workflowsResidentRecordSchema";

export const rawUsAzResidentCommon: Array<RawResidentCommon> = [
  {
    stateCode: "US_AZ",
    personExternalId: "RES001",
    pseudonymizedId: "anonres001",
    displayId: "RES001",
    personName: {
      givenNames: "Elinor",
      middleNames: "Maja",
      surname: "Sloan",
    },
    facilityId: "FACILITY1",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES002",
    pseudonymizedId: "anonres002",
    displayId: "RES002",
    personName: {
      givenNames: "Michael",
      middleNames: "James",
      surname: "Mooney",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES003",
    pseudonymizedId: "anonres003",
    displayId: "RES003",
    personName: {
      givenNames: "Sebastien",
      middleNames: "Harry",
      surname: "Bose",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES004",
    pseudonymizedId: "anonres004",
    displayId: "RES004",
    personName: {
      givenNames: "Sasha",
      middleNames: "Gideon",
      surname: "Burch",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES014",
    pseudonymizedId: "anonres014",
    displayId: "RES014",
    personName: {
      givenNames: "Carl",
      middleNames: "Benedict",
      surname: "Garrett",
    },
    facilityId: "FACILITY1",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES015",
    pseudonymizedId: "anonres015",
    displayId: "RES015",
    personName: {
      givenNames: "Rosalie",
      middleNames: "Lana",
      surname: "Bloggs",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES016",
    pseudonymizedId: "anonres016",
    displayId: "RES016",
    personName: {
      givenNames: "Kyron",
      middleNames: "Daneel",
      surname: "Christensen",
    },
    facilityId: "FACILITY3",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES017",
    pseudonymizedId: "anonres017",
    displayId: "RES017",
    personName: {
      givenNames: "Teddy",
      middleNames: "Roger",
      surname: "Villegas",
    },
    facilityId: "FACILITY1",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES018",
    pseudonymizedId: "anonres018",
    displayId: "RES018",
    personName: {
      givenNames: "Derrell",
      middleNames: "Jason",
      surname: "Stewart",
    },
    facilityId: "FACILITY1",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES019",
    pseudonymizedId: "anonres019",
    displayId: "RES019",
    personName: {
      givenNames: "Allyn",
      middleNames: "Bobby",
      surname: "Fisher",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES020",
    pseudonymizedId: "anonres020",
    displayId: "RES020",
    personName: {
      givenNames: "Hailee",
      middleNames: "Gabriella",
      surname: "Esposito",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES021",
    pseudonymizedId: "anonres021",
    displayId: "RES021",
    personName: {
      givenNames: "Marcus",
      middleNames: "Theodore",
      surname: "Rivera",
    },
    facilityId: "FACILITY1",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES022",
    pseudonymizedId: "anonres022",
    displayId: "RES022",
    personName: {
      givenNames: "Sophia",
      middleNames: "Isabella",
      surname: "Chen",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES023",
    pseudonymizedId: "anonres023",
    displayId: "RES023",
    personName: {
      givenNames: "Darius",
      middleNames: "Alexander",
      surname: "Washington",
    },
    facilityId: "FACILITY3",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES024",
    pseudonymizedId: "anonres024",
    displayId: "RES024",
    personName: {
      givenNames: "Luna",
      middleNames: "Marie",
      surname: "Garcia",
    },
    facilityId: "FACILITY1",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES025",
    pseudonymizedId: "anonres025",
    displayId: "RES025",
    personName: {
      givenNames: "Kai",
      middleNames: "James",
      surname: "Nguyen",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES026",
    pseudonymizedId: "anonres026",
    displayId: "RES026",
    personName: {
      givenNames: "Aria",
      middleNames: "Sophia",
      surname: "Patel",
    },
    facilityId: "FACILITY3",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES027",
    pseudonymizedId: "anonres027",
    displayId: "RES027",
    personName: {
      givenNames: "Jordan",
      middleNames: "Avery",
      surname: "Sinclair",
    },
    facilityId: "FACILITY1",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES028",
    pseudonymizedId: "anonres028",
    displayId: "RES028",
    personName: {
      givenNames: "Layla",
      middleNames: "Jane",
      surname: "Okafor",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES029",
    pseudonymizedId: "anonres029",
    displayId: "RES029",
    personName: {
      givenNames: "Miles",
      middleNames: "Devon",
      surname: "Carter",
    },
    facilityId: "FACILITY3",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES030",
    pseudonymizedId: "anonres030",
    displayId: "RES030",
    personName: {
      givenNames: "Nadia",
      middleNames: "Ren",
      surname: "Hoffman",
    },
    facilityId: "FACILITY1",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES031",
    pseudonymizedId: "anonres031",
    displayId: "RES031",
    personName: {
      givenNames: "Owen",
      middleNames: "Blake",
      surname: "Santos",
    },
    facilityId: "FACILITY2",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES032",
    pseudonymizedId: "anonres032",
    displayId: "RES032",
    personName: {
      givenNames: "Priya",
      middleNames: "Kim",
      surname: "Wolfe",
    },
    facilityId: "FACILITY3",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES033",
    pseudonymizedId: "anonres033",
    displayId: "RES033",
    personName: {
      givenNames: "Quinn",
      middleNames: "Ellis",
      surname: "Torres",
    },
    facilityId: "FACILITY1",
  },
  {
    stateCode: "US_AZ",
    personExternalId: "RES034",
    pseudonymizedId: "anonres034",
    displayId: "RES034",
    personName: {
      givenNames: "Dani",
      middleNames: "Reed",
      surname: "Marsh",
    },
    facilityId: "FACILITY2",
  },
];

export const usAzResidentCommon = rawUsAzResidentCommon.map((r) =>
  residentCommonSchema.parse(r),
);

export const rawUsAzResidents: Array<RawWorkflowsResidentRecord> = [
  {
    ...rawUsAzResidentCommon[0],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res001",
    gender: "FEMALE",
    unitId: "UNIT A",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -3, days: -1 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 5 }),
      projectedTprDate: relativeFixtureDate({ days: 5 }),
      tprApprovalStatus: "APPROVED",
      acisDtpDate: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 95 }),
      csbdDateV2: relativeFixtureDate({ days: 95 }),
      projectedCsbdDate: relativeFixtureDate({ days: 95 }),
      ercdDate: relativeFixtureDate({ days: 172 }),
      ercdDateV2: relativeFixtureDate({ days: 172 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: relativeFixtureDate({ months: 11 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[1],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res002",
    gender: "MALE",
    unitId: "UNIT A",
    officerId: "OFFICER2",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -4, months: -4, days: -10 }),
    releaseDate: relativeFixtureDate({ days: 518 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 50 }),
      projectedTprDate: relativeFixtureDate({ days: 50 }),
      acisDtpDate: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 140 }),
      csbdDateV2: relativeFixtureDate({ days: 140 }),
      projectedCsbdDate: relativeFixtureDate({ days: 140 }),
      ercdDate: relativeFixtureDate({ days: 217 }),
      ercdDateV2: relativeFixtureDate({ days: 217 }),
      sedDate: relativeFixtureDate({ days: 518 }),
      csedDate: relativeFixtureDate({ days: 777 }),
      stateCode: "US_AZ",
      isDprEligible: true,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[2],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res003",
    gender: "MALE",
    unitId: "UNIT B",
    officerId: "OFFICER3",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -3, months: -6, days: -18 }),
    releaseDate: relativeFixtureDate({ days: 442 }),
    metadata: {
      acisTprDate: null,
      projectedTprDate: relativeFixtureDate({ days: 27 }),
      acisDtpDate: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 117 }),
      csbdDateV2: relativeFixtureDate({ days: 117 }),
      projectedCsbdDate: relativeFixtureDate({ days: 117 }),
      ercdDate: relativeFixtureDate({ days: 194 }),
      ercdDateV2: relativeFixtureDate({ days: 194 }),
      sedDate: relativeFixtureDate({ days: 442 }),
      csedDate: relativeFixtureDate({ days: 600 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[3],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res004",
    gender: "MALE",
    unitId: "UNIT B",
    officerId: "OFFICER3",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ months: -11 }),
    releaseDate: relativeFixtureDate({ months: 20 }),
    metadata: {
      acisTprDate: null,
      projectedTprDate: relativeFixtureDate({ days: 300 }),
      acisDtpDate: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 390 }),
      csbdDateV2: relativeFixtureDate({ days: 390 }),
      projectedCsbdDate: relativeFixtureDate({ days: 390 }),
      ercdDate: relativeFixtureDate({ days: 467 }),
      ercdDateV2: relativeFixtureDate({ days: 467 }),
      sedDate: relativeFixtureDate({ months: 20 }),
      csedDate: relativeFixtureDate({ months: 23, days: 9 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[4],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res014",
    gender: "MALE",
    unitId: "UNIT B",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -3, days: -1 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 5 }),
      projectedTprDate: relativeFixtureDate({ days: 5 }),
      acisDtpDate: relativeFixtureDate({ days: 5 }),
      projectedDtpDate: relativeFixtureDate({ days: 5 }),
      dtpApprovalStatus: "APPROVED",
      csbdDate: relativeFixtureDate({ days: 95 }),
      csbdDateV2: null,
      trToAddDate: relativeFixtureDate({ days: 95 }),
      projectedCsbdDate: relativeFixtureDate({ days: 95 }),
      ercdDate: relativeFixtureDate({ days: 172 }),
      ercdDateV2: null,
      addDate: relativeFixtureDate({ days: 172 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[5],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res015",
    gender: "FEMALE",
    unitId: "UNIT C",
    officerId: "OFFICER1",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -4, months: -4, days: -10 }),
    releaseDate: relativeFixtureDate({ days: 518 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 50 }),
      projectedTprDate: relativeFixtureDate({ days: 50 }),
      acisDtpDate: relativeFixtureDate({ days: 50 }),
      projectedDtpDate: relativeFixtureDate({ days: 50 }),
      csbdDate: relativeFixtureDate({ days: 140 }),
      csbdDateV2: relativeFixtureDate({ days: 140 }),
      projectedCsbdDate: relativeFixtureDate({ days: 140 }),
      ercdDate: relativeFixtureDate({ days: 217 }),
      ercdDateV2: relativeFixtureDate({ days: 217 }),
      sedDate: relativeFixtureDate({ days: 518 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[6],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res016",
    gender: "MALE",
    unitId: "UNIT A",
    officerId: "OFFICER2",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -3, months: -6, days: -18 }),
    releaseDate: relativeFixtureDate({ days: 442 }),
    metadata: {
      acisTprDate: null,
      projectedTprDate: relativeFixtureDate({ days: 27 }),
      acisDtpDate: null,
      projectedDtpDate: relativeFixtureDate({ days: 27 }),
      csbdDate: relativeFixtureDate({ days: 117 }),
      csbdDateV2: relativeFixtureDate({ days: 117 }),
      projectedCsbdDate: relativeFixtureDate({ days: 117 }),
      ercdDate: relativeFixtureDate({ days: 194 }),
      ercdDateV2: relativeFixtureDate({ days: 194 }),
      sedDate: relativeFixtureDate({ days: 442 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[7],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res017",
    gender: "MALE",
    unitId: "UNIT A",
    officerId: "OFFICER2",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -2, days: -3 }),
    releaseDate: relativeFixtureDate({ days: 442 }),
    metadata: {
      acisTprDate: null,
      projectedTprDate: relativeFixtureDate({ days: 10 }),
      acisDtpDate: null,
      projectedDtpDate: relativeFixtureDate({ days: 10 }),
      csbdDate: relativeFixtureDate({ days: 100 }),
      csbdDateV2: relativeFixtureDate({ days: 100 }),
      projectedCsbdDate: relativeFixtureDate({ days: 100 }),
      ercdDate: relativeFixtureDate({ days: 177 }),
      ercdDateV2: relativeFixtureDate({ days: 177 }),
      sedDate: relativeFixtureDate({ days: 277 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[8],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res018",
    gender: "MALE",
    unitId: "UNIT B",
    officerId: "OFFICER3",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ months: -11 }),
    releaseDate: relativeFixtureDate({ months: 20 }),
    metadata: {
      acisTprDate: null,
      projectedTprDate: relativeFixtureDate({ days: 300 }),
      acisDtpDate: null,
      projectedDtpDate: relativeFixtureDate({ days: 300 }),
      csbdDate: relativeFixtureDate({ days: 390 }),
      csbdDateV2: relativeFixtureDate({ days: 390 }),
      projectedCsbdDate: relativeFixtureDate({ days: 390 }),
      ercdDate: relativeFixtureDate({ days: 467 }),
      ercdDateV2: relativeFixtureDate({ days: 467 }),
      sedDate: relativeFixtureDate({ months: 20 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[9],
    allEligibleOpportunities: [],
    stateCode: "US_AZ",
    recordId: "us_az_res019",
    gender: "MALE",
    unitId: "UNIT A",
    officerId: "OFFICER3",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -1, days: -5 }),
    releaseDate: relativeFixtureDate({ months: 11, days: 25 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 90 }),
      projectedTprDate: relativeFixtureDate({ days: 90 }),
      acisDtpDate: relativeFixtureDate({ days: 90 }),
      projectedDtpDate: relativeFixtureDate({ days: 90 }),
      csbdDate: relativeFixtureDate({ days: 180 }),
      csbdDateV2: relativeFixtureDate({ days: 180 }),
      projectedCsbdDate: relativeFixtureDate({ days: 180 }),
      ercdDate: relativeFixtureDate({ days: 257 }),
      ercdDateV2: relativeFixtureDate({ days: 257 }),
      sedDate: relativeFixtureDate({ months: 6 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: true,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[10],
    allEligibleOpportunities: [],
    stateCode: "US_AZ",
    recordId: "us_az_res020",
    gender: "FEMALE",
    unitId: "UNIT A",
    officerId: "OFFICER3",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -2, months: -4, days: -21 }),
    releaseDate: relativeFixtureDate({ months: 7, days: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 90 }),
      projectedTprDate: relativeFixtureDate({ days: 90 }),
      acisDtpDate: relativeFixtureDate({ days: 90 }),
      projectedDtpDate: relativeFixtureDate({ days: 90 }),
      csbdDate: relativeFixtureDate({ days: 180 }),
      csbdDateV2: relativeFixtureDate({ days: 180 }),
      projectedCsbdDate: relativeFixtureDate({ days: 180 }),
      ercdDate: relativeFixtureDate({ days: 257 }),
      ercdDateV2: relativeFixtureDate({ days: 257 }),
      sedDate: relativeFixtureDate({ months: 6 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: true,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[11],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res021",
    gender: "MALE",
    unitId: "UNIT C",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -2 }),
    releaseDate: relativeFixtureDate({ months: 8 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 45 }),
      projectedTprDate: relativeFixtureDate({ days: 45 }),
      acisDtpDate: relativeFixtureDate({ days: 45 }),
      projectedDtpDate: relativeFixtureDate({ days: 45 }),
      csbdDate: relativeFixtureDate({ days: 135 }),
      csbdDateV2: relativeFixtureDate({ days: 135 }),
      projectedCsbdDate: relativeFixtureDate({ days: 135 }),
      ercdDate: relativeFixtureDate({ days: 212 }),
      ercdDateV2: relativeFixtureDate({ days: 212 }),
      sedDate: relativeFixtureDate({ months: 8 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[12],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res022",
    gender: "FEMALE",
    unitId: "UNIT B",
    officerId: "OFFICER2",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -3, months: -1 }),
    releaseDate: relativeFixtureDate({ months: 11 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 60 }),
      projectedTprDate: relativeFixtureDate({ days: 60 }),
      acisDtpDate: relativeFixtureDate({ days: 60 }),
      projectedDtpDate: relativeFixtureDate({ days: 60 }),
      csbdDate: relativeFixtureDate({ days: 150 }),
      csbdDateV2: relativeFixtureDate({ days: 150 }),
      projectedCsbdDate: relativeFixtureDate({ days: 150 }),
      ercdDate: relativeFixtureDate({ days: 227 }),
      ercdDateV2: relativeFixtureDate({ days: 227 }),
      sedDate: relativeFixtureDate({ months: 11 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[13],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res023",
    gender: "MALE",
    unitId: "UNIT A",
    officerId: "OFFICER3",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -2, months: -3 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 75 }),
      projectedTprDate: relativeFixtureDate({ days: 75 }),
      acisDtpDate: relativeFixtureDate({ days: 75 }),
      projectedDtpDate: relativeFixtureDate({ days: 75 }),
      csbdDate: relativeFixtureDate({ days: 165 }),
      csbdDateV2: relativeFixtureDate({ days: 165 }),
      projectedCsbdDate: relativeFixtureDate({ days: 165 }),
      ercdDate: relativeFixtureDate({ days: 242 }),
      ercdDateV2: relativeFixtureDate({ days: 242 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[14],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res024",
    gender: "FEMALE",
    unitId: "UNIT B",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -6 }),
    releaseDate: relativeFixtureDate({ months: 6 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 90 }),
      projectedTprDate: relativeFixtureDate({ days: 90 }),
      acisDtpDate: relativeFixtureDate({ days: 90 }),
      projectedDtpDate: relativeFixtureDate({ days: 90 }),
      csbdDate: relativeFixtureDate({ days: 180 }),
      csbdDateV2: relativeFixtureDate({ days: 180 }),
      projectedCsbdDate: relativeFixtureDate({ days: 180 }),
      ercdDate: relativeFixtureDate({ days: 257 }),
      ercdDateV2: relativeFixtureDate({ days: 257 }),
      sedDate: relativeFixtureDate({ months: 6 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: true,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[15],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res025",
    gender: "MALE",
    unitId: "UNIT C",
    officerId: "OFFICER2",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -2, months: -5 }),
    releaseDate: relativeFixtureDate({ months: 7 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 105 }),
      projectedTprDate: relativeFixtureDate({ days: 105 }),
      acisDtpDate: relativeFixtureDate({ days: 105 }),
      projectedDtpDate: relativeFixtureDate({ days: 105 }),
      csbdDate: relativeFixtureDate({ days: 195 }),
      csbdDateV2: relativeFixtureDate({ days: 195 }),
      projectedCsbdDate: relativeFixtureDate({ days: 195 }),
      ercdDate: relativeFixtureDate({ days: 272 }),
      ercdDateV2: relativeFixtureDate({ days: 272 }),
      sedDate: relativeFixtureDate({ months: 7 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[16],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res026",
    gender: "FEMALE",
    unitId: "UNIT B",
    officerId: "OFFICER3",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -4 }),
    releaseDate: relativeFixtureDate({ months: 8 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 120 }),
      projectedTprDate: relativeFixtureDate({ days: 120 }),
      acisDtpDate: relativeFixtureDate({ days: 120 }),
      projectedDtpDate: relativeFixtureDate({ days: 120 }),
      csbdDate: relativeFixtureDate({ days: 210 }),
      csbdDateV2: relativeFixtureDate({ days: 210 }),
      projectedCsbdDate: relativeFixtureDate({ days: 210 }),
      ercdDate: relativeFixtureDate({ days: 287 }),
      ercdDateV2: relativeFixtureDate({ days: 287 }),
      sedDate: relativeFixtureDate({ months: 8 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[17],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res027",
    gender: "MALE",
    unitId: "UNIT A",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -2, months: -3 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: -5 }),
      projectedTprDate: relativeFixtureDate({ days: -5 }),
      tprApprovalStatus: "APPROVED",
      acisDtpDate: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 85 }),
      csbdDateV2: relativeFixtureDate({ days: 85 }),
      projectedCsbdDate: relativeFixtureDate({ days: 85 }),
      ercdDate: relativeFixtureDate({ days: 162 }),
      ercdDateV2: relativeFixtureDate({ days: 162 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: relativeFixtureDate({ months: 11 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[18],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res028",
    gender: "FEMALE",
    unitId: "UNIT B",
    officerId: "OFFICER2",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -6 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 45 }),
      projectedTprDate: relativeFixtureDate({ days: 45 }),
      tprApprovalStatus: "APPROVED",
      acisDtpDate: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 135 }),
      csbdDateV2: relativeFixtureDate({ days: 135 }),
      projectedCsbdDate: relativeFixtureDate({ days: 135 }),
      ercdDate: relativeFixtureDate({ days: 212 }),
      ercdDateV2: relativeFixtureDate({ days: 212 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: relativeFixtureDate({ months: 11 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[19],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res029",
    gender: "MALE",
    unitId: "UNIT A",
    officerId: "OFFICER3",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -4 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 15 }),
      projectedTprDate: relativeFixtureDate({ days: 15 }),
      acisDtpDate: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 105 }),
      csbdDateV2: relativeFixtureDate({ days: 105 }),
      projectedCsbdDate: relativeFixtureDate({ days: 105 }),
      ercdDate: relativeFixtureDate({ days: 182 }),
      ercdDateV2: relativeFixtureDate({ days: 182 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: relativeFixtureDate({ months: 11 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[20],
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    recordId: "us_az_res030",
    gender: "FEMALE",
    unitId: "UNIT B",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -2, months: -1 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: -5 }),
      projectedTprDate: relativeFixtureDate({ days: -5 }),
      acisDtpDate: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 85 }),
      csbdDateV2: relativeFixtureDate({ days: 85 }),
      projectedCsbdDate: relativeFixtureDate({ days: 85 }),
      ercdDate: relativeFixtureDate({ days: 162 }),
      ercdDateV2: relativeFixtureDate({ days: 162 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: relativeFixtureDate({ months: 11 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[21],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res031",
    gender: "MALE",
    unitId: "UNIT C",
    officerId: "OFFICER2",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -2, months: -5 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: -5 }),
      projectedTprDate: relativeFixtureDate({ days: -5 }),
      acisDtpDate: relativeFixtureDate({ days: -5 }),
      projectedDtpDate: relativeFixtureDate({ days: -5 }),
      dtpApprovalStatus: "APPROVED",
      csbdDate: relativeFixtureDate({ days: 85 }),
      csbdDateV2: null,
      trToAddDate: relativeFixtureDate({ days: 85 }),
      projectedCsbdDate: relativeFixtureDate({ days: 85 }),
      ercdDate: relativeFixtureDate({ days: 162 }),
      ercdDateV2: null,
      addDate: relativeFixtureDate({ days: 162 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[22],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res032",
    gender: "FEMALE",
    unitId: "UNIT B",
    officerId: "OFFICER3",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -9 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 45 }),
      projectedTprDate: relativeFixtureDate({ days: 45 }),
      acisDtpDate: relativeFixtureDate({ days: 45 }),
      projectedDtpDate: relativeFixtureDate({ days: 45 }),
      dtpApprovalStatus: "APPROVED",
      csbdDate: relativeFixtureDate({ days: 135 }),
      csbdDateV2: null,
      trToAddDate: relativeFixtureDate({ days: 135 }),
      projectedCsbdDate: relativeFixtureDate({ days: 135 }),
      ercdDate: relativeFixtureDate({ days: 212 }),
      ercdDateV2: null,
      addDate: relativeFixtureDate({ days: 212 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[23],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res033",
    gender: "MALE",
    unitId: "UNIT C",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -8 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: -5 }),
      projectedTprDate: relativeFixtureDate({ days: -5 }),
      acisDtpDate: relativeFixtureDate({ days: -5 }),
      projectedDtpDate: relativeFixtureDate({ days: -5 }),
      csbdDate: relativeFixtureDate({ days: 85 }),
      csbdDateV2: null,
      trToAddDate: relativeFixtureDate({ days: 85 }),
      projectedCsbdDate: relativeFixtureDate({ days: 85 }),
      ercdDate: relativeFixtureDate({ days: 162 }),
      ercdDateV2: null,
      addDate: relativeFixtureDate({ days: 162 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    ...rawUsAzResidentCommon[24],
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    recordId: "us_az_res034",
    gender: "FEMALE",
    unitId: "UNIT A",
    officerId: "OFFICER2",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -7 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 15 }),
      projectedTprDate: relativeFixtureDate({ days: 15 }),
      acisDtpDate: relativeFixtureDate({ days: 15 }),
      projectedDtpDate: relativeFixtureDate({ days: 15 }),
      csbdDate: relativeFixtureDate({ days: 105 }),
      csbdDateV2: null,
      trToAddDate: relativeFixtureDate({ days: 105 }),
      projectedCsbdDate: relativeFixtureDate({ days: 105 }),
      ercdDate: relativeFixtureDate({ days: 182 }),
      ercdDateV2: null,
      addDate: relativeFixtureDate({ days: 182 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      csedDate: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
];

export const usAzResidents = rawUsAzResidents.map((r) =>
  workflowsResidentRecordSchema.parse(r),
);
