// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2025 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

import { relativeFixtureDate } from "../../../utils/zod";
import { RawResidentRecord, residentRecordSchema } from "../schema";

export const rawUsAzResidents: Array<RawResidentRecord> = [
  {
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    personExternalId: "RES001",
    recordId: "us_az_res001",
    displayId: "RES001",
    personName: {
      givenNames: "Elinor",
      middleNames: "Maja",
      surname: "Sloan",
    },
    gender: "FEMALE",
    pseudonymizedId: "anonres001",
    facilityId: "FACILITY1",
    unitId: "UNIT A",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -3, days: -1 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 5 }),
      acisTprDateRaw: relativeFixtureDate({ days: 5 }),
      projectedTprDate: relativeFixtureDate({ days: 5 }),
      acisDtpDate: null,
      acisDtpDateRaw: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 95 }),
      csbdDateRaw: relativeFixtureDate({ days: 95 }),
      projectedCsbdDate: relativeFixtureDate({ days: 95 }),
      ercdDate: relativeFixtureDate({ days: 172 }),
      ercdDateRaw: relativeFixtureDate({ days: 172 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      sedDateRaw: relativeFixtureDate({ months: 9 }),
      csedDate: relativeFixtureDate({ months: 11 }),
      csedDateRaw: relativeFixtureDate({ months: 11 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    personExternalId: "RES002",
    recordId: "us_az_res002",
    displayId: "RES002",
    personName: {
      givenNames: "Michael",
      middleNames: "James",
      surname: "Mooney",
    },
    gender: "MALE",
    pseudonymizedId: "anonres002",
    facilityId: "FACILITY2",
    unitId: "UNIT A",
    officerId: "OFFICER2",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -4, months: -4, days: -10 }),
    releaseDate: relativeFixtureDate({ days: 518 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 50 }),
      acisTprDateRaw: relativeFixtureDate({ days: 50 }),
      projectedTprDate: relativeFixtureDate({ days: 50 }),
      acisDtpDate: null,
      acisDtpDateRaw: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 140 }),
      csbdDateRaw: relativeFixtureDate({ days: 140 }),
      projectedCsbdDate: relativeFixtureDate({ days: 140 }),
      ercdDate: relativeFixtureDate({ days: 217 }),
      ercdDateRaw: relativeFixtureDate({ days: 217 }),
      sedDate: relativeFixtureDate({ days: 518 }),
      sedDateRaw: relativeFixtureDate({ days: 518 }),
      csedDate: relativeFixtureDate({ days: 777 }),
      csedDateRaw: relativeFixtureDate({ days: 777 }),
      stateCode: "US_AZ",
      isDprEligible: true,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    personExternalId: "RES003",
    recordId: "us_az_res003",
    displayId: "RES003",
    personName: {
      givenNames: "Sebastien",
      middleNames: "Harry",
      surname: "Bose",
    },
    gender: "MALE",
    pseudonymizedId: "anonres003",
    facilityId: "FACILITY2",
    unitId: "UNIT B",
    officerId: "OFFICER3",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -3, months: -6, days: -18 }),
    releaseDate: relativeFixtureDate({ days: 442 }),
    metadata: {
      acisTprDate: null,
      acisTprDateRaw: null,
      projectedTprDate: relativeFixtureDate({ days: 27 }),
      acisDtpDate: null,
      acisDtpDateRaw: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 117 }),
      csbdDateRaw: relativeFixtureDate({ days: 117 }),
      projectedCsbdDate: relativeFixtureDate({ days: 117 }),
      ercdDate: relativeFixtureDate({ days: 194 }),
      ercdDateRaw: relativeFixtureDate({ days: 194 }),
      sedDate: relativeFixtureDate({ days: 442 }),
      sedDateRaw: relativeFixtureDate({ days: 442 }),
      csedDate: relativeFixtureDate({ days: 600 }),
      csedDateRaw: relativeFixtureDate({ days: 600 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    personExternalId: "RES004",
    recordId: "us_az_res004",
    displayId: "RES004",
    personName: {
      givenNames: "Sasha",
      middleNames: "Gideon",
      surname: "Burch",
    },
    gender: "MALE",
    pseudonymizedId: "anonres004",
    facilityId: "FACILITY2",
    unitId: "UNIT B",
    officerId: "OFFICER3",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ months: -11 }),
    releaseDate: relativeFixtureDate({ months: 20 }),
    metadata: {
      acisTprDate: null,
      acisTprDateRaw: null,
      projectedTprDate: relativeFixtureDate({ days: 300 }),
      acisDtpDate: null,
      acisDtpDateRaw: null,
      projectedDtpDate: null,
      csbdDate: relativeFixtureDate({ days: 390 }),
      csbdDateRaw: relativeFixtureDate({ days: 390 }),
      projectedCsbdDate: relativeFixtureDate({ days: 390 }),
      ercdDate: relativeFixtureDate({ days: 467 }),
      ercdDateRaw: relativeFixtureDate({ days: 467 }),
      sedDate: relativeFixtureDate({ months: 20 }),
      sedDateRaw: relativeFixtureDate({ months: 20 }),
      csedDate: relativeFixtureDate({ months: 23, days: 9 }),
      csedDateRaw: relativeFixtureDate({ months: 23, days: 9 }),
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    personExternalId: "RES014",
    recordId: "us_az_res014",
    displayId: "RES014",
    personName: {
      givenNames: "Carl",
      middleNames: "Benedict",
      surname: "Garrett",
    },
    gender: "MALE",
    pseudonymizedId: "anonres014",
    facilityId: "FACILITY1",
    unitId: "UNIT B",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -3, days: -1 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 5 }),
      acisTprDateRaw: null,
      projectedTprDate: relativeFixtureDate({ days: 5 }),
      acisDtpDate: relativeFixtureDate({ days: 5 }),
      acisDtpDateRaw: null,
      projectedDtpDate: relativeFixtureDate({ days: 5 }),
      csbdDate: relativeFixtureDate({ days: 95 }),
      csbdDateRaw: null,
      trToAddDateRaw: relativeFixtureDate({ days: 95 }),
      projectedCsbdDate: relativeFixtureDate({ days: 95 }),
      ercdDate: relativeFixtureDate({ days: 172 }),
      ercdDateRaw: null,
      addDateRaw: relativeFixtureDate({ days: 172 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      sedDateRaw: relativeFixtureDate({ months: 9 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    personExternalId: "RES015",
    recordId: "us_az_res015",
    displayId: "RES015",
    personName: {
      givenNames: "Rosalie",
      middleNames: "Lana",
      surname: "Bloggs",
    },
    gender: "FEMALE",
    pseudonymizedId: "anonres015",
    facilityId: "FACILITY2",
    unitId: "UNIT C",
    officerId: "OFFICER1",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -4, months: -4, days: -10 }),
    releaseDate: relativeFixtureDate({ days: 518 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 50 }),
      acisTprDateRaw: relativeFixtureDate({ days: 50 }),
      projectedTprDate: relativeFixtureDate({ days: 50 }),
      acisDtpDate: relativeFixtureDate({ days: 50 }),
      acisDtpDateRaw: relativeFixtureDate({ days: 50 }),
      projectedDtpDate: relativeFixtureDate({ days: 50 }),
      csbdDate: relativeFixtureDate({ days: 140 }),
      csbdDateRaw: relativeFixtureDate({ days: 140 }),
      projectedCsbdDate: relativeFixtureDate({ days: 140 }),
      ercdDate: relativeFixtureDate({ days: 217 }),
      ercdDateRaw: relativeFixtureDate({ days: 217 }),
      sedDate: relativeFixtureDate({ days: 518 }),
      sedDateRaw: relativeFixtureDate({ days: 518 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    personExternalId: "RES016",
    recordId: "us_az_res016",
    displayId: "RES016",
    personName: {
      givenNames: "Kyron",
      middleNames: "Daneel",
      surname: "Christensen",
    },
    gender: "MALE",
    pseudonymizedId: "anonres016",
    facilityId: "FACILITY3",
    unitId: "UNIT A",
    officerId: "OFFICER2",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -3, months: -6, days: -18 }),
    releaseDate: relativeFixtureDate({ days: 442 }),
    metadata: {
      acisTprDate: null,
      acisTprDateRaw: null,
      projectedTprDate: relativeFixtureDate({ days: 27 }),
      acisDtpDate: null,
      acisDtpDateRaw: null,
      projectedDtpDate: relativeFixtureDate({ days: 27 }),
      csbdDate: relativeFixtureDate({ days: 117 }),
      csbdDateRaw: relativeFixtureDate({ days: 117 }),
      projectedCsbdDate: relativeFixtureDate({ days: 117 }),
      ercdDate: relativeFixtureDate({ days: 194 }),
      ercdDateRaw: relativeFixtureDate({ days: 194 }),
      sedDate: relativeFixtureDate({ days: 442 }),
      sedDateRaw: relativeFixtureDate({ days: 442 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    personExternalId: "RES017",
    recordId: "us_az_res017",
    displayId: "RES017",
    personName: {
      givenNames: "Teddy",
      middleNames: "Roger",
      surname: "Villegas",
    },
    gender: "MALE",
    pseudonymizedId: "anonres017",
    facilityId: "FACILITY1",
    unitId: "UNIT A",
    officerId: "OFFICER2",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -2, days: -3 }),
    releaseDate: relativeFixtureDate({ days: 442 }),
    metadata: {
      acisTprDate: null,
      acisTprDateRaw: null,
      projectedTprDate: relativeFixtureDate({ days: 10 }),
      acisDtpDate: null,
      acisDtpDateRaw: null,
      projectedDtpDate: relativeFixtureDate({ days: 10 }),
      csbdDate: relativeFixtureDate({ days: 100 }),
      csbdDateRaw: relativeFixtureDate({ days: 100 }),
      projectedCsbdDate: relativeFixtureDate({ days: 100 }),
      ercdDate: relativeFixtureDate({ days: 177 }),
      ercdDateRaw: relativeFixtureDate({ days: 177 }),
      sedDate: relativeFixtureDate({ days: 277 }),
      sedDateRaw: relativeFixtureDate({ days: 277 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    personExternalId: "RES018",
    recordId: "us_az_res018",
    displayId: "RES018",
    personName: {
      givenNames: "Derrell",
      middleNames: "Jason",
      surname: "Stewart",
    },
    gender: "MALE",
    pseudonymizedId: "anonres018",
    facilityId: "FACILITY1",
    unitId: "UNIT B",
    officerId: "OFFICER3",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ months: -11 }),
    releaseDate: relativeFixtureDate({ months: 20 }),
    metadata: {
      acisTprDate: null,
      acisTprDateRaw: null,
      projectedTprDate: relativeFixtureDate({ days: 300 }),
      acisDtpDate: null,
      acisDtpDateRaw: null,
      projectedDtpDate: relativeFixtureDate({ days: 300 }),
      csbdDate: relativeFixtureDate({ days: 390 }),
      csbdDateRaw: relativeFixtureDate({ days: 390 }),
      projectedCsbdDate: relativeFixtureDate({ days: 390 }),
      ercdDate: relativeFixtureDate({ days: 467 }),
      ercdDateRaw: relativeFixtureDate({ days: 467 }),
      sedDate: relativeFixtureDate({ months: 20 }),
      sedDateRaw: relativeFixtureDate({ months: 20 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: [],
    stateCode: "US_AZ",
    personExternalId: "RES019",
    recordId: "us_az_res019",
    displayId: "RES019",
    personName: {
      givenNames: "Allyn",
      middleNames: "Bobby",
      surname: "Fisher",
    },
    gender: "MALE",
    pseudonymizedId: "anonres019",
    facilityId: "FACILITY2",
    unitId: "UNIT A",
    officerId: "OFFICER3",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -1, days: -5 }),
    releaseDate: relativeFixtureDate({ months: 11, days: 25 }),
    metadata: {},
  },
  {
    allEligibleOpportunities: [],
    stateCode: "US_AZ",
    personExternalId: "RES020",
    recordId: "us_az_res020",
    displayId: "RES020",
    personName: {
      givenNames: "Hailee",
      middleNames: "Gabriella",
      surname: "Esposito",
    },
    gender: "FEMALE",
    pseudonymizedId: "anonres020",
    facilityId: "FACILITY2",
    unitId: "UNIT A",
    officerId: "OFFICER3",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -2, months: -4, days: -21 }),
    releaseDate: relativeFixtureDate({ months: 7, days: 9 }),
    metadata: {},
  },
  {
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    personExternalId: "RES021",
    recordId: "us_az_res021",
    displayId: "RES021",
    personName: {
      givenNames: "Marcus",
      middleNames: "Theodore",
      surname: "Rivera",
    },
    gender: "MALE",
    pseudonymizedId: "anonres021",
    facilityId: "FACILITY1",
    unitId: "UNIT C",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -2 }),
    releaseDate: relativeFixtureDate({ months: 8 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 45 }),
      acisTprDateRaw: relativeFixtureDate({ days: 45 }),
      projectedTprDate: relativeFixtureDate({ days: 45 }),
      acisDtpDate: relativeFixtureDate({ days: 45 }),
      acisDtpDateRaw: relativeFixtureDate({ days: 45 }),
      projectedDtpDate: relativeFixtureDate({ days: 45 }),
      csbdDate: relativeFixtureDate({ days: 135 }),
      csbdDateRaw: relativeFixtureDate({ days: 135 }),
      projectedCsbdDate: relativeFixtureDate({ days: 135 }),
      ercdDate: relativeFixtureDate({ days: 212 }),
      ercdDateRaw: relativeFixtureDate({ days: 212 }),
      sedDate: relativeFixtureDate({ months: 8 }),
      sedDateRaw: relativeFixtureDate({ months: 8 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    personExternalId: "RES022",
    recordId: "us_az_res022",
    displayId: "RES022",
    personName: {
      givenNames: "Sophia",
      middleNames: "Isabella",
      surname: "Chen",
    },
    gender: "FEMALE",
    pseudonymizedId: "anonres022",
    facilityId: "FACILITY2",
    unitId: "UNIT B",
    officerId: "OFFICER2",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -3, months: -1 }),
    releaseDate: relativeFixtureDate({ months: 11 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 60 }),
      acisTprDateRaw: relativeFixtureDate({ days: 60 }),
      projectedTprDate: relativeFixtureDate({ days: 60 }),
      acisDtpDate: relativeFixtureDate({ days: 60 }),
      acisDtpDateRaw: relativeFixtureDate({ days: 60 }),
      projectedDtpDate: relativeFixtureDate({ days: 60 }),
      csbdDate: relativeFixtureDate({ days: 150 }),
      csbdDateRaw: relativeFixtureDate({ days: 150 }),
      projectedCsbdDate: relativeFixtureDate({ days: 150 }),
      ercdDate: relativeFixtureDate({ days: 227 }),
      ercdDateRaw: relativeFixtureDate({ days: 227 }),
      sedDate: relativeFixtureDate({ months: 11 }),
      sedDateRaw: relativeFixtureDate({ months: 11 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToTPR"],
    stateCode: "US_AZ",
    personExternalId: "RES023",
    recordId: "us_az_res023",
    displayId: "RES023",
    personName: {
      givenNames: "Darius",
      middleNames: "Alexander",
      surname: "Washington",
    },
    gender: "MALE",
    pseudonymizedId: "anonres023",
    facilityId: "FACILITY3",
    unitId: "UNIT A",
    officerId: "OFFICER3",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -2, months: -3 }),
    releaseDate: relativeFixtureDate({ months: 9 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 75 }),
      acisTprDateRaw: relativeFixtureDate({ days: 75 }),
      projectedTprDate: relativeFixtureDate({ days: 75 }),
      acisDtpDate: relativeFixtureDate({ days: 75 }),
      acisDtpDateRaw: relativeFixtureDate({ days: 75 }),
      projectedDtpDate: relativeFixtureDate({ days: 75 }),
      csbdDate: relativeFixtureDate({ days: 165 }),
      csbdDateRaw: relativeFixtureDate({ days: 165 }),
      projectedCsbdDate: relativeFixtureDate({ days: 165 }),
      ercdDate: relativeFixtureDate({ days: 242 }),
      ercdDateRaw: relativeFixtureDate({ days: 242 }),
      sedDate: relativeFixtureDate({ months: 9 }),
      sedDateRaw: relativeFixtureDate({ months: 9 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    personExternalId: "RES024",
    recordId: "us_az_res024",
    displayId: "RES024",
    personName: {
      givenNames: "Luna",
      middleNames: "Marie",
      surname: "Garcia",
    },
    gender: "FEMALE",
    pseudonymizedId: "anonres024",
    facilityId: "FACILITY1",
    unitId: "UNIT B",
    officerId: "OFFICER1",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -6 }),
    releaseDate: relativeFixtureDate({ months: 6 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 90 }),
      acisTprDateRaw: relativeFixtureDate({ days: 90 }),
      projectedTprDate: relativeFixtureDate({ days: 90 }),
      acisDtpDate: relativeFixtureDate({ days: 90 }),
      acisDtpDateRaw: relativeFixtureDate({ days: 90 }),
      projectedDtpDate: relativeFixtureDate({ days: 90 }),
      csbdDate: relativeFixtureDate({ days: 180 }),
      csbdDateRaw: relativeFixtureDate({ days: 180 }),
      projectedCsbdDate: relativeFixtureDate({ days: 180 }),
      ercdDate: relativeFixtureDate({ days: 257 }),
      ercdDateRaw: relativeFixtureDate({ days: 257 }),
      sedDate: relativeFixtureDate({ months: 6 }),
      sedDateRaw: relativeFixtureDate({ months: 15 }),
      csedDate: null,
      csedDateRaw: relativeFixtureDate({ months: 13 }),
      stateCode: "US_AZ",
      isDprEligible: true,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    personExternalId: "RES025",
    recordId: "us_az_res025",
    displayId: "RES025",
    personName: {
      givenNames: "Kai",
      middleNames: "James",
      surname: "Nguyen",
    },
    gender: "MALE",
    pseudonymizedId: "anonres025",
    facilityId: "FACILITY2",
    unitId: "UNIT C",
    officerId: "OFFICER2",
    custodyLevel: "MEDIUM",
    admissionDate: relativeFixtureDate({ years: -2, months: -5 }),
    releaseDate: relativeFixtureDate({ months: 7 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 105 }),
      acisTprDateRaw: relativeFixtureDate({ days: 105 }),
      projectedTprDate: relativeFixtureDate({ days: 105 }),
      acisDtpDate: relativeFixtureDate({ days: 105 }),
      acisDtpDateRaw: relativeFixtureDate({ days: 105 }),
      projectedDtpDate: relativeFixtureDate({ days: 105 }),
      csbdDate: relativeFixtureDate({ days: 195 }),
      csbdDateRaw: relativeFixtureDate({ days: 195 }),
      projectedCsbdDate: relativeFixtureDate({ days: 195 }),
      ercdDate: relativeFixtureDate({ days: 272 }),
      ercdDateRaw: relativeFixtureDate({ days: 272 }),
      sedDate: relativeFixtureDate({ months: 7 }),
      sedDateRaw: relativeFixtureDate({ months: 7 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
  {
    allEligibleOpportunities: ["usAzReleaseToDTP"],
    stateCode: "US_AZ",
    personExternalId: "RES026",
    recordId: "us_az_res026",
    displayId: "RES026",
    personName: {
      givenNames: "Aria",
      middleNames: "Sophia",
      surname: "Patel",
    },
    gender: "FEMALE",
    pseudonymizedId: "anonres026",
    facilityId: "FACILITY3",
    unitId: "UNIT B",
    officerId: "OFFICER3",
    custodyLevel: "MINIMUM",
    admissionDate: relativeFixtureDate({ years: -1, months: -4 }),
    releaseDate: relativeFixtureDate({ months: 8 }),
    metadata: {
      acisTprDate: relativeFixtureDate({ days: 120 }),
      acisTprDateRaw: relativeFixtureDate({ days: 120 }),
      projectedTprDate: relativeFixtureDate({ days: 120 }),
      acisDtpDate: relativeFixtureDate({ days: 120 }),
      acisDtpDateRaw: relativeFixtureDate({ days: 120 }),
      projectedDtpDate: relativeFixtureDate({ days: 120 }),
      csbdDate: relativeFixtureDate({ days: 210 }),
      csbdDateRaw: relativeFixtureDate({ days: 210 }),
      projectedCsbdDate: relativeFixtureDate({ days: 210 }),
      ercdDate: relativeFixtureDate({ days: 287 }),
      ercdDateRaw: relativeFixtureDate({ days: 287 }),
      sedDate: relativeFixtureDate({ months: 8 }),
      sedDateRaw: relativeFixtureDate({ months: 8 }),
      csedDate: null,
      csedDateRaw: null,
      stateCode: "US_AZ",
      isDprEligible: false,
      hasAnyDprProgramCompleted: false,
      lastUpdatedDate: relativeFixtureDate({ days: -1 }),
    },
  },
];

export const usAzResidents = rawUsAzResidents.map((r) =>
  residentRecordSchema.parse(r),
);
