apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: recidiviz-force-db-demo
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: "recidiviz-rnd-planner:us-central1:recidiviz-demo"
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          maxRetries: 3
          timeoutSeconds: 3600
          containers:
          - name: recidiviz-force-db-demo
            image: gcr.io/recidiviz-rnd-planner/recidiviz-force-db-job:latest
            env:
              - name: RECIDIVIZ_DEPLOY_ENV
                value: "gcp"
              - name: RECIDIVIZ_GCP_DB_INSTANCE_NAME
                value: "recidiviz-rnd-planner:us-central1:recidiviz-demo"
              - name: RECIDIVIZ_REDIS_URL
                value: "redis://10.205.183.251:6379"
              - name: RECIDIVIZ_POSTGRES_USER
                value: "postgres"
              - name: RECIDIVIZ_POSTGRES_SERVER
                value: "/cloudsql/recidiviz-rnd-planner:us-central1:recidiviz-demo"
              - name: RECIDIVIZ_POSTGRES_PORT
                value: "5432"
              - name: RECIDIVIZ_POSTGRES_DB
                value: "recidiviz"
              - name: RECIDIVIZ_LANGCHAIN_TRACING_V2
                value: "true"
              - name: RECIDIVIZ_LANGCHAIN_ENDPOINT
                value: "https://api.smith.langchain.com"
              - name: RECIDIVIZ_VCR_CLIENT_INTAKE
                value: "true"
              - name: RECIDIVIZ_ALLOWED_ORIGINS
                value: "https://frontend-demo-773019812766.us-central1.run.app"
              - name: RECIDIVIZ_LANGCHAIN_PROJECT
                value: "dev-recidiviz"
              - name: RECIDIVIZ_EXTERNAL_RESOURCES_API_URL
                value: "https://resources-api-773019812766.us-central1.run.app"
              - name: RECIDIVIZ_ENABLE_AUTH_MIDDLEWARE
                value: "true"
              - name: RECIDIVIZ_AUTH0_AUDIENCE
                value: "https://recidiviz-rnd.us.auth0.com/api/v2/"
              - name: RECIDIVIZ_AUTH0_DOMAIN
                value: "recidiviz-rnd.us.auth0.com"
              - name: RECIDIVIZ_USE_EXTERNAL_RESOURCES_API
                value: "true"
              - name: RECIDIVIZ_GCS_BUCKET_NAME
                value: "recidiviz-dev-bucket-1"
              - name: RECIDIVIZ_JWT_ALGORITHM
                value: "HS256"
              - name: RECIDIVIZ_LANGCHAIN_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: RECIDIVIZ_LANGCHAIN_API_KEY_DEMO
                    key: "1"
              - name: RECIDIVIZ_OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: RECIDIVIZ_OPENAI_API_KEY_DEMO
                    key: "1"
              - name: RECIDIVIZ_FABRK_BEARER_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: RECIDIVIZ_FABRK_BEARER_TOKEN_DEMO
                    key: "1"
              - name: RECIDIVIZ_POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: RECIDIVIZ_POSTGRES_PASSWORD_DEMO
                    key: "1"
              - name: RECIDIVIZ_RESOURCES_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: RECIDIVIZ_RESOURCES_API_KEY_DEMO
                    key: "1"
              - name: RECIDIVIZ_AUTH0_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: RECIDIVIZ_AUTH0_CLIENT_ID_DEMO
                    key: "1"
              - name: RECIDIVIZ_JWT_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: RECIDIVIZ_JWT_SECRET_KEY_DEMO
                    key: "1"
              - name: RECIDIVIZ_BQ_PROJECT_ID
                valueFrom:
                  secretKeyRef:
                    name: RECIDIVIZ_BQ_PROJECT_ID_DEMO
                    key: "1"
              - name: RECIDIVIZ_BQ_DATASET
                valueFrom:
                  secretKeyRef:
                    name: RECIDIVIZ_BQ_DATASET_DEMO
                    key: "1"
            resources:
              limits:
                cpu: "1"
                memory: "512Mi"
