# Defines services needed to run the Workflows end to end tests
# Run via `docker compose -f docker-compose.e2e.yaml up`

version: "3"

services:
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    labels:
      app: pulse-dashboards-e2e

  app:
    # This image is built using e2e.Dockerfile and manually pushed to Dockerhub
    image: danrecidiviz/firebase-tools-react:latest
    working_dir: /home/node/app/dist/apps/staff
    volumes:
      - ../../:/home/node/app
    command: serve -s
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "nwget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1",
        ]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
    user: node
    labels:
      app: pulse-dashboards-e2e

  server:
    image: danrecidiviz/firebase-tools-react:latest
    working_dir: /home/node/app/apps/staff
    volumes:
      - ../../:/home/node/app
    command: yarn run env-cmd -f .env.offline node server.js
    ports:
      - "3001:3001"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "nwget --no-verbose --tries=1 --spider http://localhost:3001/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 3
    environment:
      - REDISHOST=redis
      - REDISPORT=6379
    user: node
    labels:
      app: pulse-dashboards-e2e

  firebase:
    image: danrecidiviz/firebase-tools-react:latest
    working_dir: /home/node/app
    volumes:
      - ../../:/home/node/app
    command: yarn nx firebase-offline staff
    environment:
      - ENABLE_UI=true
      - GCP_PROJECT=demo-dev
    ports:
      - "4000:4000"
      - "4400:4400"
      - "8080:8080"
      - "9099:9099"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "nwget --no-verbose --tries=1 --spider http://localhost:4000/ || exit 1",
        ]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
    # Firebase requires write access to `firestore-debug.log` inside the /home/node/app volume
    # The emulator needs to run as root since the volume is owned by the `root` user in the  Github action runner
    user: root
    labels:
      app: pulse-dashboards-e2e
