repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
        files: ^apps/@reentry/backend/.*
      - id: trailing-whitespace
        files: ^apps/@reentry/backend/.*

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    files: ^apps/@reentry/backend/.*
    hooks:
      - id: ruff
        args: [--fix]
        files: ^apps/@reentry/backend/.*
      - id: ruff-format
        files: ^apps/@reentry/backend/.*