// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2026 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

// Reconciles each collection's live schema against the declarations in
// src/schemas/index.ts and applies non-destructive add/drop mutations via
// Typesense's PATCH endpoint (`client.collections(name).update(...)`).
//
// This is the deploy-safe path for evolving schemas. Unlike `provision.ts
// -- --recreate`, this preserves all existing documents — adds new fields as
// `null`/`undefined` on existing docs (backfill populates later) and strips
// dropped fields from existing docs immediately.
//
// Decisions:
//   - Collection missing in Typesense -> CREATE with the local schema.
//   - Field in local but not live -> ADD via PATCH. MUST be `optional: true`.
//   - Field in live but not local -> DROP via PATCH.
//   - Field exists in both with different `type` or different attribute values
//     (facet, optional, etc.) -> ABORT. Typesense can't mutate field
//     attributes in place; the operator must drop + re-add manually.
//   - Collection-level settings (enable_nested_fields, default_sorting_field)
//     differ -> ABORT. Same reason — recreate required.
//
// Flags:
//   --dry-run   Print the plan and exit without mutating anything.
//
// Reads TYPESENSE_HOST and TYPESENSE_ADMIN_API_KEY from the env (SOPS-loaded
// when invoked through the nx target). Admin scope is required because PATCH
// is a `collections:*` action.

/* eslint-disable no-await-in-loop --
 * Sequential awaits are intentional throughout the apply step. Each collection
 * gets one PATCH (or CREATE) and we want a clean per-collection log line on
 * success/failure — parallelizing would interleave output AND risk colliding
 * with Typesense's "another collection update operation in progress" guard if
 * multiple PATCHes ever targeted the same collection.
 */

import type { CollectionUpdateSchema } from "typesense/lib/Typesense/Collection";
import type { CollectionCreateSchema } from "typesense/lib/Typesense/Collections";

import { createTypesenseClient } from "./client";
import { schemas } from "./schemas";

type LocalField = NonNullable<CollectionCreateSchema["fields"]>[number];
type LiveField = LocalField & { drop?: boolean };

function hasFlag(name: string): boolean {
  return process.argv.some(
    (arg) => arg === `--${name}` || arg === `--${name}=true`,
  );
}

// Attributes we compare when checking for in-place modifications. Anything
// declared on the local field is enforced; anything we DON'T declare locally
// is left to Typesense's defaults (no enforcement, no false-positive conflicts).
const COMPARED_ATTRS = [
  "type",
  "facet",
  "optional",
  "index",
  "sort",
  "infix",
  "stem",
] as const;

export interface SchemaDiff {
  collection: string;
  toAdd: LocalField[];
  toDrop: string[];
  // Field-level conflicts that the operator must resolve manually.
  fieldConflicts: Array<{ field: string; reason: string }>;
  // Collection-level setting conflicts (enable_nested_fields, etc.).
  collectionConflicts: string[];
}

// True when `name` is auto-generated by Typesense as a nested child of an
// object-type field declared in the local schema. With enable_nested_fields,
// declaring `{ name: "personName", type: "object" }` causes Typesense to
// auto-index leaf fields like `personName.givenNames` — those appear in the
// schema response but are NOT separately declarable locally. Filtering them
// out of the drop set prevents the migration from trying to drop fields it
// doesn't own.
export function isAutoNestedChild(
  fieldName: string,
  objectFieldNames: ReadonlySet<string>,
): boolean {
  const dot = fieldName.indexOf(".");
  if (dot === -1) return false;
  return objectFieldNames.has(fieldName.slice(0, dot));
}

export function diffSchema(
  local: CollectionCreateSchema,
  live: {
    fields?: LiveField[];
    enable_nested_fields?: boolean;
    default_sorting_field?: string;
  },
): SchemaDiff {
  const localFields = local.fields ?? [];
  const liveFields = live.fields ?? [];

  const liveByName = new Map(liveFields.map((f) => [f.name, f]));
  const localByName = new Map(localFields.map((f) => [f.name, f]));

  // Parent names for nested-field auto-expansion (see isAutoNestedChild).
  const localObjectFieldNames = new Set(
    localFields
      .filter((f) => f.type === "object" || f.type === "object[]")
      .map((f) => f.name),
  );

  const diff: SchemaDiff = {
    collection: local.name,
    toAdd: [],
    toDrop: [],
    fieldConflicts: [],
    collectionConflicts: [],
  };

  // Adds: declared locally, missing live.
  for (const f of localFields) {
    if (!liveByName.has(f.name)) diff.toAdd.push(f);
  }

  // Drops: present live, not declared locally — but skip auto-generated
  // nested children whose parent IS declared locally.
  for (const f of liveFields) {
    if (localByName.has(f.name)) continue;
    if (isAutoNestedChild(f.name, localObjectFieldNames)) continue;
    diff.toDrop.push(f.name);
  }

  // Field-level conflicts: same name in both, but at least one attribute we
  // care about differs. Typesense can't mutate field attributes in place.
  for (const f of localFields) {
    const liveField = liveByName.get(f.name);
    if (!liveField) continue;
    for (const attr of COMPARED_ATTRS) {
      const localVal = (f as Record<string, unknown>)[attr];
      const liveVal = (liveField as Record<string, unknown>)[attr];
      // We only enforce attrs the local schema explicitly declares.
      if (localVal === undefined) continue;
      if (localVal !== liveVal) {
        diff.fieldConflicts.push({
          field: f.name,
          reason: `attribute "${attr}" changed (local=${JSON.stringify(localVal)}, live=${JSON.stringify(liveVal)}). Typesense can't mutate field attributes in place — drop + re-add manually.`,
        });
      }
    }
  }

  // Collection-level conflicts. enable_nested_fields and default_sorting_field
  // are immutable in Typesense.
  if (
    local.enable_nested_fields !== undefined &&
    live.enable_nested_fields !== undefined &&
    local.enable_nested_fields !== live.enable_nested_fields
  ) {
    diff.collectionConflicts.push(
      `enable_nested_fields changed (local=${local.enable_nested_fields}, live=${live.enable_nested_fields}) — immutable; collection recreate required.`,
    );
  }
  if (
    local.default_sorting_field !== undefined &&
    live.default_sorting_field !== undefined &&
    local.default_sorting_field !== live.default_sorting_field
  ) {
    diff.collectionConflicts.push(
      `default_sorting_field changed (local=${local.default_sorting_field}, live=${live.default_sorting_field}) — immutable; collection recreate required.`,
    );
  }

  return diff;
}

// New fields MUST be optional. A non-optional add forces every existing doc to
// be invalid against the new schema until backfill catches up — searches on
// the new field error out in the meantime.
export function checkOptionalOnAdds(diff: SchemaDiff): string[] {
  return diff.toAdd
    .filter((f) => f.optional !== true)
    .map(
      (f) =>
        `${diff.collection}.${f.name} is being added but lacks { optional: true }. Make it optional in schemas/index.ts — existing docs won't have the field until backfill, and non-optional would break searches in the interim.`,
    );
}

async function main(): Promise<void> {
  const host = process.env["TYPESENSE_HOST"];
  const apiKey = process.env["TYPESENSE_ADMIN_API_KEY"];
  if (!host) {
    console.error("TYPESENSE_HOST is required");
    process.exit(1);
  }
  if (!apiKey) {
    console.error(
      "TYPESENSE_ADMIN_API_KEY is required (admin scope — NOT the search-only TYPESENSE_API_KEY)",
    );
    process.exit(1);
  }

  const dryRun = hasFlag("dry-run");
  // Schema PATCH on object-type fields (with auto-expanded children) can take
  // tens of seconds on collections with non-trivial doc counts. The client's
  // default 5s timeout is set for search/document traffic and is too short
  // here — the request appears to fail client-side while the server keeps
  // applying the change, and the auto-retry then 422s with "Another collection
  // update operation is in progress." 120s gives schema ops comfortable
  // headroom.
  const client = createTypesenseClient({
    host,
    apiKey,
    connectionTimeoutSeconds: 120,
  });

  const liveCollections = await client.collections().retrieve();
  const liveByName = new Map(liveCollections.map((c) => [c.name, c]));

  type PlanEntry =
    | { collection: string; action: "create"; schema: CollectionCreateSchema }
    | { collection: string; action: "patch"; diff: SchemaDiff }
    | { collection: string; action: "noop" };

  const plan: PlanEntry[] = [];
  const errors: string[] = [];

  for (const schema of schemas) {
    const live = liveByName.get(schema.name);
    if (!live) {
      plan.push({ collection: schema.name, action: "create", schema });
      continue;
    }
    const diff = diffSchema(schema, live as never);
    if (diff.fieldConflicts.length > 0) {
      for (const c of diff.fieldConflicts) {
        errors.push(`[${diff.collection}.${c.field}] ${c.reason}`);
      }
    }
    if (diff.collectionConflicts.length > 0) {
      for (const c of diff.collectionConflicts) {
        errors.push(`[${diff.collection}] ${c}`);
      }
    }
    errors.push(...checkOptionalOnAdds(diff));

    if (diff.toAdd.length === 0 && diff.toDrop.length === 0) {
      plan.push({ collection: schema.name, action: "noop" });
    } else {
      plan.push({ collection: schema.name, action: "patch", diff });
    }
  }

  console.info(dryRun ? "Plan (dry run — nothing will be applied):" : "Plan:");
  for (const p of plan) {
    if (p.action === "noop") {
      console.info(`  [${p.collection}] no changes`);
    } else if (p.action === "create") {
      console.info(`  [${p.collection}] CREATE (collection does not exist)`);
    } else {
      const adds = p.diff.toAdd.length
        ? p.diff.toAdd.map((f) => `+${f.name}`).join(", ")
        : "(no adds)";
      const drops = p.diff.toDrop.length
        ? p.diff.toDrop.map((n) => `-${n}`).join(", ")
        : "(no drops)";
      console.info(`  [${p.collection}] PATCH — ${adds}; ${drops}`);
    }
  }

  if (errors.length > 0) {
    console.error("\nErrors — refusing to mutate the cluster:");
    for (const e of errors) console.error(`  ${e}`);
    process.exit(1);
  }

  if (dryRun) {
    console.info("\nDry run complete. Re-run without --dry-run to apply.");
    return;
  }

  // Apply. Adds and drops in a single PATCH per collection; creates one-by-one.
  let mutated = 0;
  for (const p of plan) {
    if (p.action === "noop") continue;
    if (p.action === "create") {
      await client.collections().create(p.schema);
      console.info(`[${p.collection}] created`);
      mutated += 1;
      continue;
    }
    const updateBody: CollectionUpdateSchema = {
      fields: [
        ...p.diff.toAdd,
        ...p.diff.toDrop.map((name) => ({ name, drop: true as const })),
      ],
    };
    await client.collections(p.collection).update(updateBody);
    console.info(`[${p.collection}] patched`);
    mutated += 1;
  }

  console.info(`\nDone — ${mutated} collection(s) mutated.`);
}

// Only auto-run main() when this file is invoked directly (e.g. via tsx),
// not when imported by tests. Otherwise importing the module's pure helpers
// in vitest would also trigger main() — which exits the process when env
// vars are missing.
if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    const message = err instanceof Error ? err.message : String(err);
    console.error(message);
    process.exit(1);
  });
}
