// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2025 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

import { compiler } from "markdown-to-jsx";
import { JSX } from "react";

/**
 * Extracts all h2 heading IDs from the markdown content in order.
 * Returns an array of URL hash IDs generated by markdown-to-jsx.
 *
 * @param markdownContent - The markdown content to parse
 * @returns Array of heading IDs (e.g., ["transition-program-releases", "standard-transition-program", ...])
 */
export function extractHeadingIds(markdownContent: string): string[] {
  try {
    const bodyElements = compiler(markdownContent, {
      wrapper: null,
    }) as unknown as Array<JSX.Element>;

    const h2Elements = bodyElements.filter((e) => e.type === "h2");

    return h2Elements.map((heading) => heading.props.id);
  } catch (e) {
    console.error("Failed to parse markdown headings:", e);
    return [];
  }
}
