steps:
  # Build the container image
  # Built-in vairables
  # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/backend:demo"
      - "-t"
      - "gcr.io/$PROJECT_ID/backend:$COMMIT_SHA"
      - "-f"
      - "deploy/Dockerfile.gcp"
      - "."

  # Push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "--all-tags", "gcr.io/$PROJECT_ID/backend"]

  # Deploy API service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "backend-api-demo"
      - "--image"
      - "gcr.io/$PROJECT_ID/backend:demo"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--timeout"
      - "1000"
      - "--cpu"
      - "1"
      - "--memory"
      - "1Gi"
      - "--add-cloudsql-instances"
      - "recidiviz-rnd-planner:us-central1:recidiviz-demo"
      - "--service-account"
      - "773019812766-compute@developer.gserviceaccount.com"
      - "--set-secrets=RECIDIVIZ_LANGCHAIN_API_KEY=RECIDIVIZ_LANGCHAIN_API_KEY_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_OPENAI_API_KEY=RECIDIVIZ_OPENAI_API_KEY_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_FABRK_BEARER_TOKEN=RECIDIVIZ_FABRK_BEARER_TOKEN_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_POSTGRES_PASSWORD=RECIDIVIZ_POSTGRES_PASSWORD_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_RESOURCES_API_KEY=RECIDIVIZ_RESOURCES_API_KEY_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_AUTH0_CLIENT_ID=RECIDIVIZ_AUTH0_CLIENT_ID_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_JWT_SECRET_KEY=RECIDIVIZ_JWT_SECRET_KEY_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_BQ_PROJECT_ID=RECIDIVIZ_BQ_PROJECT_ID_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_BQ_DATASET=RECIDIVIZ_BQ_DATASET_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_DEEPGRAM_API_KEY=RECIDIVIZ_DEEPGRAM_API_KEY:latest"
      - "--set-env-vars"
      - |
        ENTRYPOINT=api,
        RECIDIVIZ_ENV_NAME=demo,
        RECIDIVIZ_DEPLOY_ENV=gcp,
        RECIDIVIZ_GCP_DB_INSTANCE_NAME=recidiviz-rnd-planner:us-central1:recidiviz-demo,
        RECIDIVIZ_REDIS_URL=redis://10.205.183.251:6379,
        RECIDIVIZ_POSTGRES_USER=postgres,
        RECIDIVIZ_POSTGRES_SERVER=/cloudsql/recidiviz-rnd-planner:us-central1:recidiviz-demo,
        RECIDIVIZ_POSTGRES_PORT=5432,
        RECIDIVIZ_POSTGRES_DB=recidiviz,
        RECIDIVIZ_LANGCHAIN_TRACING_V2=true,
        RECIDIVIZ_LANGCHAIN_ENDPOINT=https://api.smith.langchain.com,
        RECIDIVIZ_VCR_CLIENT_INTAKE=true,
        RECIDIVIZ_ALLOWED_ORIGINS=https://plan-demo.recidiviz.org,
        RECIDIVIZ_LANGCHAIN_PROJECT=dev-recidiviz,
        RECIDIVIZ_EXTERNAL_RESOURCES_API_URL=https://resources-api-773019812766.us-central1.run.app,
        RECIDIVIZ_ENABLE_AUTH_MIDDLEWARE=true,
        RECIDIVIZ_AUTH0_AUDIENCE=https://recidiviz-rnd.us.auth0.com/api/v2/,
        RECIDIVIZ_AUTH0_DOMAIN=recidiviz-rnd.us.auth0.com,
        RECIDIVIZ_USE_EXTERNAL_RESOURCES_API=true,
        RECIDIVIZ_JWT_ALGORITHM=HS256,
        RECIDIVIZ_BQ_CASE_MANAGER_TABLE=case_manager_demo,
        RECIDIVIZ_BQ_SUPERVISION_OFFICER_TABLE=supervision_officer_demo,
        RECIDIVIZ_BQ_CLIENT_TABLE=client_demo,
        RECIDIVIZ_GCS_BUCKET_NAME=recidiviz-recording-bucket-demo,
        RECIDIVIZ_GCS_SERVICE_ACCOUNT_EMAIL=773019812766-compute@developer.gserviceaccount.com,
        RECIDIVIZ_SENTRY_DSN=https://68c6d6b1c76579ebee3b9b8d785eda5a@o432474.ingest.us.sentry.io/4509651398819840,
        RECIDIVIZ_DIARIZATION_SERVICE=deepgram,
        CHECKFINALCHARACTERHERE=todo:pending-to-fix

  # Deploy Worker service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "backend-worker-demo"
      - "--image"
      - "gcr.io/$PROJECT_ID/backend:demo"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--timeout"
      - "1000"
      - "--cpu"
      - "1"
      - "--memory"
      - "1Gi"
      - "--add-cloudsql-instances"
      - "recidiviz-rnd-planner:us-central1:recidiviz-demo"
      - "--service-account"
      - "773019812766-compute@developer.gserviceaccount.com"
      - "--no-cpu-throttling"
      - "--set-secrets=RECIDIVIZ_LANGCHAIN_API_KEY=RECIDIVIZ_LANGCHAIN_API_KEY_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_OPENAI_API_KEY=RECIDIVIZ_OPENAI_API_KEY_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_FABRK_BEARER_TOKEN=RECIDIVIZ_FABRK_BEARER_TOKEN_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_POSTGRES_PASSWORD=RECIDIVIZ_POSTGRES_PASSWORD_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_AUTH0_CLIENT_ID=RECIDIVIZ_AUTH0_CLIENT_ID_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_RESOURCES_API_KEY=RECIDIVIZ_RESOURCES_API_KEY_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_JWT_SECRET_KEY=RECIDIVIZ_JWT_SECRET_KEY_DEMO:latest"
      - "--set-secrets=RECIDIVIZ_DEEPGRAM_API_KEY=RECIDIVIZ_DEEPGRAM_API_KEY:latest"
      - "--set-env-vars"
      - |
        ENTRYPOINT=worker,
        RECIDIVIZ_ENV_NAME=demo,
        RECIDIVIZ_DEPLOY_ENV=gcp,
        RECIDIVIZ_GCP_DB_INSTANCE_NAME=recidiviz-rnd-planner:us-central1:recidiviz-demo,
        RECIDIVIZ_REDIS_URL=redis://10.205.183.251:6379,
        RECIDIVIZ_POSTGRES_USER=postgres,
        RECIDIVIZ_POSTGRES_SERVER=/cloudsql/recidiviz-rnd-planner:us-central1:recidiviz-demo,
        RECIDIVIZ_POSTGRES_PORT=5432,
        RECIDIVIZ_POSTGRES_DB=recidiviz,
        RECIDIVIZ_LANGCHAIN_TRACING_V2=true,
        RECIDIVIZ_LANGCHAIN_ENDPOINT=https://api.smith.langchain.com,
        RECIDIVIZ_LANGCHAIN_PROJECT=dev-recidiviz,
        RECIDIVIZ_VCR_CLIENT_INTAKE=true,
        RECIDIVIZ_EXTERNAL_RESOURCES_API_URL=https://resources-api-773019812766.us-central1.run.app,
        RECIDIVIZ_ENABLE_AUTH_MIDDLEWARE=true,
        RECIDIVIZ_AUTH0_AUDIENCE=https://recidiviz-rnd.us.auth0.com/api/v2/,
        RECIDIVIZ_AUTH0_DOMAIN=recidiviz-rnd.us.auth0.com,
        RECIDIVIZ_USE_EXTERNAL_RESOURCES_API=true,
        RECIDIVIZ_JWT_ALGORITHM=HS256,
        RECIDIVIZ_ALLOWED_ORIGINS=http://34.107.140.51,
        RECIDIVIZ_GCS_BUCKET_NAME=recidiviz-recording-bucket-demo,
        RECIDIVIZ_GCS_SERVICE_ACCOUNT_EMAIL=773019812766-compute@developer.gserviceaccount.com,
        RECIDIVIZ_DIARIZATION_SERVICE=deepgram,
        RECIDIVIZ_SENTRY_DSN=https://68c6d6b1c76579ebee3b9b8d785eda5a@o432474.ingest.us.sentry.io/4509651398819840

  # Route traffic to latest revision
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "-q"
      - "run"
      - "services"
      - "update-traffic"
      - "backend-api-demo"
      - "--project"
      - "$PROJECT_ID"
      - "--region"
      - "us-central1"
      - "--to-latest"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "-q"
      - "run"
      - "services"
      - "update-traffic"
      - "backend-worker-demo"
      - "--project"
      - "$PROJECT_ID"
      - "--region"
      - "us-central1"
      - "--to-latest"

images:
  - "gcr.io/$PROJECT_ID/backend:demo"
  - "gcr.io/$PROJECT_ID/backend:$COMMIT_SHA"
